//go:build with_cv
// +build with_cv

// Tests auto-generated by AI agent.
package privacyblur

import (
	"context"
	"sync/atomic"
	"testing"

	testifyassert "github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestNewBlurFaces(t *testing.T) {
	enabled := &atomic.Bool{}
	enabled.Store(true)

	pb, err := NewBlurFaces(enabled)
	require.NoError(t, err)
	defer pb.Close(context.Background())

	testifyassert.Contains(t, pb.String(), "face")
	testifyassert.Equal(t, float64(15), pb.BlurRadius.Load())
}

func TestNewBlurPlates(t *testing.T) {
	enabled := &atomic.Bool{}
	enabled.Store(true)

	pb, err := NewBlurPlates(enabled)
	require.NoError(t, err)
	defer pb.Close(context.Background())

	testifyassert.Contains(t, pb.String(), "plate")
}

func TestNewBlurAll(t *testing.T) {
	enabled := &atomic.Bool{}
	enabled.Store(true)

	pb, err := NewBlurAll(enabled)
	require.NoError(t, err)
	defer pb.Close(context.Background())

	s := pb.String()
	testifyassert.Contains(t, s, "face")
	testifyassert.Contains(t, s, "plate")
}

func TestNewBlurFaces_NilEnabled(t *testing.T) {
	pb, err := NewBlurFaces(nil)
	require.NoError(t, err)
	defer pb.Close(context.Background())

	// Enabled should be nil (always on).
	testifyassert.Nil(t, pb.Enabled)
}

func TestNewNode(t *testing.T) {
	ctx := context.Background()
	pb, err := NewBlurFaces(nil)
	require.NoError(t, err)

	n := NewNode(ctx, pb)
	require.NotNil(t, n)
	testifyassert.NotNil(t, n.Processor)
}
