package streammux

// Tests generated by agent: differential testing of Go production code against
// Lean spec (proofs/Spec/StreamMux/BitrateControl.lean).

import (
	"context"
	"math"
	"testing"
	"time"

	testassert "github.com/stretchr/testify/assert"
	testrequire "github.com/stretchr/testify/require"
	"github.com/xaionaro-go/avpipeline/codec"
	"github.com/xaionaro-go/avpipeline/preset/streammux/types"
)

// ---------------------------------------------------------------------------
// Lean spec reference implementations (pure, using the same types as Go)
// ---------------------------------------------------------------------------

// leanEffectiveMaxBitRate mirrors BitrateControl.lean effectiveMaxBitRate.
// Lean uses Int; we use float64 (Ubps) to match the Go type.
func leanEffectiveMaxBitRate(minBitRate, maxBitRate, inputBitRate types.Ubps) types.Ubps {
	if inputBitRate > minBitRate*2 && 1.5*inputBitRate < maxBitRate {
		return 1.5 * inputBitRate
	}
	return maxBitRate
}

// leanClampBitRate mirrors BitrateControl.lean clampBitRate.
func leanClampBitRate(minBitRate, maxBitRate, inputBitRate, bitrate types.Ubps) types.Ubps {
	mx := leanEffectiveMaxBitRate(minBitRate, maxBitRate, inputBitRate)
	if bitrate < minBitRate {
		return minBitRate
	}
	if bitrate > mx {
		return mx
	}
	return bitrate
}

// leanShouldEnableBypass mirrors BitrateControl.lean shouldEnableBypass.
func leanShouldEnableBypass(bitrate, inputBitRate types.Ubps) bool {
	return 5*bitrate > 6*inputBitRate
}

// leanShouldDisableBypass mirrors BitrateControl.lean shouldDisableBypass.
func leanShouldDisableBypass(bitrate, inputBitRate types.Ubps) bool {
	return bitrate < inputBitRate
}

// ---------------------------------------------------------------------------
// Target 1: clampBitRate / effectiveMaxBitRate
// ---------------------------------------------------------------------------

func TestLeanSpec_EffectiveMaxBitRate(t *testing.T) {
	testCases := []struct {
		name         string
		minBitRate   types.Ubps
		maxBitRate   types.Ubps
		inputBitRate types.Ubps
		wantMax      types.Ubps
	}{
		{
			name:         "input above 2*min and 1.5*input below max: effective max is 1.5*input",
			minBitRate:   1_000_000,
			maxBitRate:   24_000_000,
			inputBitRate: 6_000_000,
			wantMax:      9_000_000,
		},
		{
			name:         "input exactly 2*min: condition fails (not strictly greater)",
			minBitRate:   1_000_000,
			maxBitRate:   24_000_000,
			inputBitRate: 2_000_000,
			wantMax:      24_000_000,
		},
		{
			name:         "input barely above 2*min",
			minBitRate:   1_000_000,
			maxBitRate:   24_000_000,
			inputBitRate: 2_000_001,
			wantMax:      3_000_001.5,
		},
		{
			name:         "1.5*input equals max: condition fails (not strictly less)",
			minBitRate:   1_000_000,
			maxBitRate:   9_000_000,
			inputBitRate: 6_000_000,
			wantMax:      9_000_000,
		},
		{
			name:         "1.5*input barely below max",
			minBitRate:   1_000_000,
			maxBitRate:   9_000_002,
			inputBitRate: 6_000_000,
			wantMax:      9_000_000,
		},
		{
			name:         "input zero",
			minBitRate:   1_000_000,
			maxBitRate:   24_000_000,
			inputBitRate: 0,
			wantMax:      24_000_000,
		},
		{
			name:         "input negative (degenerate)",
			minBitRate:   1_000_000,
			maxBitRate:   24_000_000,
			inputBitRate: -1,
			wantMax:      24_000_000,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Test the Lean reference impl
			got := leanEffectiveMaxBitRate(tc.minBitRate, tc.maxBitRate, tc.inputBitRate)
			testassert.InDelta(t, float64(tc.wantMax), float64(got), 0.01,
				"lean reference: effectiveMax mismatch")

			// Now verify Go production code uses the same logic.
			// We reconstruct the Go clamping inline (from trySetVideoBitrate lines 597-608).
			maxVideoBitRate := tc.maxBitRate
			if tc.inputBitRate > tc.minBitRate*2 && float64(tc.inputBitRate)*1.5 < float64(maxVideoBitRate) {
				maxVideoBitRate = types.Ubps(1.5 * float64(tc.inputBitRate))
			}
			testassert.InDelta(t, float64(tc.wantMax), float64(maxVideoBitRate), 0.01,
				"Go production: effectiveMax mismatch")
		})
	}
}

func TestLeanSpec_ClampBitRate(t *testing.T) {
	testCases := []struct {
		name         string
		minBitRate   types.Ubps
		maxBitRate   types.Ubps
		inputBitRate types.Ubps
		bitrate      types.Ubps
		want         types.Ubps
	}{
		{
			name:         "bitrate within range, no effective-max reduction",
			minBitRate:   1_000_000,
			maxBitRate:   24_000_000,
			inputBitRate: 10_000_000,
			bitrate:      8_000_000,
			want:         8_000_000,
		},
		{
			name:         "bitrate below min: clamped to min",
			minBitRate:   1_000_000,
			maxBitRate:   24_000_000,
			inputBitRate: 10_000_000,
			bitrate:      500_000,
			want:         1_000_000,
		},
		{
			name:         "bitrate above effective max: clamped to effective max",
			minBitRate:   1_000_000,
			maxBitRate:   24_000_000,
			inputBitRate: 6_000_000,
			bitrate:      20_000_000,
			want:         9_000_000, // effective max = 1.5 * 6M = 9M
		},
		{
			name:         "bitrate above max, no effective-max reduction",
			minBitRate:   1_000_000,
			maxBitRate:   24_000_000,
			inputBitRate: 20_000_000,
			bitrate:      30_000_000,
			want:         24_000_000,
		},
		{
			name:         "effective max clamping does not go below min",
			minBitRate:   5_000_000,
			maxBitRate:   24_000_000,
			inputBitRate: 12_000_000, // 12M > 2*5M, 18M < 24M => effectiveMax=18M
			bitrate:      20_000_000,
			want:         18_000_000,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			leanResult := leanClampBitRate(tc.minBitRate, tc.maxBitRate, tc.inputBitRate, tc.bitrate)
			testassert.InDelta(t, float64(tc.want), float64(leanResult), 0.01,
				"lean reference: clamp mismatch")

			// Reproduce Go clamping logic (trySetVideoBitrate lines 597-608)
			maxVideoBitRate := tc.maxBitRate
			if tc.inputBitRate > tc.minBitRate*2 && float64(tc.inputBitRate)*1.5 < float64(maxVideoBitRate) {
				maxVideoBitRate = types.Ubps(1.5 * float64(tc.inputBitRate))
			}
			clamped := tc.bitrate
			switch {
			case tc.bitrate < tc.minBitRate:
				clamped = tc.minBitRate
			case tc.bitrate > maxVideoBitRate:
				clamped = maxVideoBitRate
			}
			testassert.InDelta(t, float64(tc.want), float64(clamped), 0.01,
				"Go production: clamp mismatch")
		})
	}
}

// ---------------------------------------------------------------------------
// Target 2: checkSlowdown
// ---------------------------------------------------------------------------

func TestLeanSpec_CheckSlowdown_NoPreviousRequest(t *testing.T) {
	// Lean: match prev with | none => notThisTime ⟨isUpgrade, now, now⟩
	// Go: prevRequest == nil → create new request, return ErrNotThisTime{}
	cfg := AutoBitRateVideoConfig{
		ResolutionUpgradeSlowdownMinDuration: time.Second * 15,
		ResolutionDowngradeSlowdownDuration:  time.Second * 2,
		ResolutionsAndBitRates: AutoBitRateResolutionAndBitRateConfigs{
			{Resolution: codec.Resolution{Width: 1920, Height: 1080}, BitrateHigh: 8_000_000, BitrateLow: 3_000_000},
		},
	}

	h := &AutoBitRateHandler[any]{AutoBitRateVideoConfig: cfg}
	testassert.Nil(t, h.currentResolutionChangeRequest,
		"precondition: no previous request")

	key := &SenderKey{VideoResolution: codec.Resolution{Width: 1920, Height: 1080}}
	err := h.checkSlowdown(context.Background(), true, key)
	testassert.ErrorAs(t, err, &ErrNotThisTime{},
		"first call should return ErrNotThisTime")
	testrequire.NotNil(t, h.currentResolutionChangeRequest,
		"should have created a new request")
	testassert.True(t, h.currentResolutionChangeRequest.IsUpgrade)
}

func TestLeanSpec_CheckSlowdown_DirectionChange(t *testing.T) {
	// Lean: if p.isUpgrade != isUpgrade => notThisTime ⟨isUpgrade, now, now⟩
	cfg := AutoBitRateVideoConfig{
		ResolutionUpgradeSlowdownMinDuration: time.Second * 15,
		ResolutionDowngradeSlowdownDuration:  time.Second * 2,
		ResolutionsAndBitRates: AutoBitRateResolutionAndBitRateConfigs{
			{Resolution: codec.Resolution{Width: 1920, Height: 1080}, BitrateHigh: 8_000_000, BitrateLow: 3_000_000},
		},
	}
	h := &AutoBitRateHandler[any]{AutoBitRateVideoConfig: cfg}

	// Set up an upgrade request
	now := time.Now()
	h.currentResolutionChangeRequest = &resolutionChangeRequest{
		IsUpgrade: true,
		StartedAt: now.Add(-time.Second * 20), // long enough to pass upgrade slowdown
		LatestAt:  now,
	}

	key := &SenderKey{VideoResolution: codec.Resolution{Width: 1280, Height: 720}}
	// Now request a DOWNGRADE (direction change)
	err := h.checkSlowdown(context.Background(), false, key)
	testassert.ErrorAs(t, err, &ErrNotThisTime{},
		"direction change should reset and return ErrNotThisTime")
	testrequire.NotNil(t, h.currentResolutionChangeRequest)
	testassert.False(t, h.currentResolutionChangeRequest.IsUpgrade,
		"should have reset to downgrade direction")
}

func TestLeanSpec_CheckSlowdown_StaleRequest(t *testing.T) {
	// Lean: now - p.latestAt > 60000 => notThisTime ⟨isUpgrade, now, now⟩
	cfg := AutoBitRateVideoConfig{
		ResolutionUpgradeSlowdownMinDuration: time.Second * 15,
		ResolutionDowngradeSlowdownDuration:  time.Second * 2,
		ResolutionsAndBitRates: AutoBitRateResolutionAndBitRateConfigs{
			{Resolution: codec.Resolution{Width: 1920, Height: 1080}, BitrateHigh: 8_000_000, BitrateLow: 3_000_000},
		},
	}
	h := &AutoBitRateHandler[any]{AutoBitRateVideoConfig: cfg}

	// Simulate a stale request (LatestAt > 1 minute ago)
	now := time.Now()
	h.currentResolutionChangeRequest = &resolutionChangeRequest{
		IsUpgrade: true,
		StartedAt: now.Add(-time.Minute * 5),
		LatestAt:  now.Add(-time.Minute - time.Second), // > 1 minute ago
	}

	key := &SenderKey{VideoResolution: codec.Resolution{Width: 1920, Height: 1080}}
	err := h.checkSlowdown(context.Background(), true, key) // same direction
	testassert.ErrorAs(t, err, &ErrNotThisTime{},
		"stale request should reset and return ErrNotThisTime")
	testrequire.NotNil(t, h.currentResolutionChangeRequest)
	// The new request should have StartedAt close to now
	testassert.WithinDuration(t, time.Now(), h.currentResolutionChangeRequest.StartedAt, time.Second)
}

func TestLeanSpec_CheckSlowdown_UpgradeWaitThenProceed(t *testing.T) {
	// Lean: if isUpgrade && reqDur >= effectiveUpgradeMs => proceed
	cfg := AutoBitRateVideoConfig{
		ResolutionUpgradeSlowdownMinDuration: time.Second * 15,
		ResolutionDowngradeSlowdownDuration:  time.Second * 2,
		ResolutionsAndBitRates: AutoBitRateResolutionAndBitRateConfigs{
			{Resolution: codec.Resolution{Width: 1920, Height: 1080}, BitrateHigh: 8_000_000, BitrateLow: 3_000_000},
		},
	}
	h := &AutoBitRateHandler[any]{AutoBitRateVideoConfig: cfg}

	now := time.Now()
	h.currentResolutionChangeRequest = &resolutionChangeRequest{
		IsUpgrade: true,
		StartedAt: now.Add(-time.Second * 16), // 16s > 15s threshold
		LatestAt:  now.Add(-time.Second),
	}

	key := &SenderKey{VideoResolution: codec.Resolution{Width: 1920, Height: 1080}}
	err := h.checkSlowdown(context.Background(), true, key)
	testassert.NoError(t, err, "should proceed after waiting long enough")
	testassert.Nil(t, h.currentResolutionChangeRequest,
		"should have cleared the request after proceeding")
}

func TestLeanSpec_CheckSlowdown_DowngradeFastProceed(t *testing.T) {
	// Lean: if !isUpgrade && reqDur >= downgradeSlowdownMs => proceed
	cfg := AutoBitRateVideoConfig{
		ResolutionUpgradeSlowdownMinDuration: time.Second * 15,
		ResolutionDowngradeSlowdownDuration:  time.Second * 2,
		ResolutionsAndBitRates: AutoBitRateResolutionAndBitRateConfigs{
			{Resolution: codec.Resolution{Width: 1280, Height: 720}, BitrateHigh: 4_000_000, BitrateLow: 2_000_000},
		},
	}
	h := &AutoBitRateHandler[any]{AutoBitRateVideoConfig: cfg}

	now := time.Now()
	h.currentResolutionChangeRequest = &resolutionChangeRequest{
		IsUpgrade: false,
		StartedAt: now.Add(-time.Second * 3), // 3s > 2s downgrade threshold
		LatestAt:  now.Add(-time.Millisecond * 500),
	}

	key := &SenderKey{VideoResolution: codec.Resolution{Width: 1280, Height: 720}}
	err := h.checkSlowdown(context.Background(), false, key)
	testassert.NoError(t, err, "downgrade should proceed after 3s (threshold 2s)")
}

func TestLeanSpec_CheckSlowdown_DowngradeStillWaiting(t *testing.T) {
	// Lean: if !isUpgrade && reqDur < downgradeSlowdownMs => notThisTime
	cfg := AutoBitRateVideoConfig{
		ResolutionUpgradeSlowdownMinDuration: time.Second * 15,
		ResolutionDowngradeSlowdownDuration:  time.Second * 2,
		ResolutionsAndBitRates: AutoBitRateResolutionAndBitRateConfigs{
			{Resolution: codec.Resolution{Width: 1280, Height: 720}, BitrateHigh: 4_000_000, BitrateLow: 2_000_000},
		},
	}
	h := &AutoBitRateHandler[any]{AutoBitRateVideoConfig: cfg}

	now := time.Now()
	h.currentResolutionChangeRequest = &resolutionChangeRequest{
		IsUpgrade: false,
		StartedAt: now.Add(-time.Second * 1), // 1s < 2s threshold
		LatestAt:  now.Add(-time.Millisecond * 100),
	}

	key := &SenderKey{VideoResolution: codec.Resolution{Width: 1280, Height: 720}}
	err := h.checkSlowdown(context.Background(), false, key)
	testassert.ErrorAs(t, err, &ErrNotThisTime{},
		"downgrade should still be waiting after 1s (threshold 2s)")
}

// ---------------------------------------------------------------------------
// Target 3: temporaryReduceFPS formula
// ---------------------------------------------------------------------------

// leanTemporaryReduceFPS computes the new multiplier per the Lean spec.
// Returns (newNum, newDen, ok). ok==false means rate-limited.
func leanTemporaryReduceFPS(
	prevNum, prevDen int,
	bitrate, bitrateBeyondThreshold, curEncodedBitRate types.Ubps,
	elapsedMs int,
) (newNum, newDen int, ok bool) {
	if elapsedMs < 1000 {
		return 0, 0, false
	}
	s0Num := prevNum * int(bitrate)
	s0Den := prevDen * int(curEncodedBitRate)
	s1Num := int(bitrate)
	s1Den := int(bitrate - bitrateBeyondThreshold)
	newNum = s0Num*s1Den + s1Num*s0Den
	newDen = 2 * s0Den * s1Den
	return newNum, newDen, true
}

func TestLeanSpec_TemporaryReduceFPS_Formula(t *testing.T) {
	// Verify the core formula: the average of two sources.
	// source0 = (prevNum/prevDen) * (bitrate/curEncodedBitRate)
	// source1 = bitrate / (bitrate - bitrateBeyondThreshold)
	// result = (source0 + source1) / 2 as a rational

	testCases := []struct {
		name                   string
		prevNum, prevDen       int
		bitrate                types.Ubps
		bitrateBeyondThreshold types.Ubps // negative
		curEncodedBitRate      types.Ubps
	}{
		{
			name:                   "typical downgrade scenario",
			prevNum:                1,
			prevDen:                1,
			bitrate:                2_000_000,
			bitrateBeyondThreshold: -1_000_000, // 1M below threshold
			curEncodedBitRate:      3_000_000,
		},
		{
			name:                   "already reduced multiplier",
			prevNum:                3,
			prevDen:                4,
			bitrate:                1_500_000,
			bitrateBeyondThreshold: -500_000,
			curEncodedBitRate:      2_000_000,
		},
		{
			name:                   "bitrate equals encoded bitrate",
			prevNum:                1,
			prevDen:                1,
			bitrate:                5_000_000,
			bitrateBeyondThreshold: -2_000_000,
			curEncodedBitRate:      5_000_000,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			leanNum, leanDen, ok := leanTemporaryReduceFPS(
				tc.prevNum, tc.prevDen,
				tc.bitrate, tc.bitrateBeyondThreshold, tc.curEncodedBitRate,
				2000, // 2s elapsed, above 1s threshold
			)
			testrequire.True(t, ok, "should not be rate-limited")

			leanFloat := float64(leanNum) / float64(leanDen)

			// Reproduce Go formula (temporaryReduceFPS lines 1077-1079)
			prevFloat := float64(tc.prevNum) / float64(tc.prevDen)
			goSource0 := prevFloat * float64(tc.bitrate) / float64(tc.curEncodedBitRate)
			goSource1 := float64(tc.bitrate) / float64(tc.bitrate-tc.bitrateBeyondThreshold)
			goAvg := (goSource0 + goSource1) / 2

			testassert.InDelta(t, leanFloat, goAvg, 1e-9,
				"Lean rational (%d/%d = %f) should match Go float avg (%f)",
				leanNum, leanDen, leanFloat, goAvg)
		})
	}
}

func TestLeanSpec_TemporaryReduceFPS_RateLimited(t *testing.T) {
	// Lean: if nowMs - st.updatedAtMs < 1000 then none
	_, _, ok := leanTemporaryReduceFPS(1, 1, 2_000_000, -1_000_000, 3_000_000, 999)
	testassert.False(t, ok, "should be rate-limited when elapsed < 1000ms")
}

// ---------------------------------------------------------------------------
// Target 3 BUG: temporaryReduceFPS receives unclamped bitrate but clamped
// bitrateBeyondThreshold. The Lean spec computes both from the same bitrate.
// ---------------------------------------------------------------------------

func TestLeanSpec_TemporaryReduceFPS_MixedClampedUnclamped(t *testing.T) {
	// Scenario:
	// - MinBitRate = 20000
	// - Current resolution 720p: BitrateLow = 2000000, BitrateHigh = 4000000
	// - Calculator requests req.BitRate = 15000 (below MinBitRate)
	// - Clamped bitrate = 20000
	// - bitrateBeyondThreshold = clampedBitRate - BitrateLow = 20000 - 2000000 = -1980000
	// - temporaryReduceFPS receives (req.BitRate=15000, bitrateBeyondThreshold=-1980000)
	//
	// The Lean spec would use the SAME bitrate value for both:
	// If using clamped: bitrate=20000, beyond=20000-2000000=-1980000
	//   s1 = 20000 / (20000 - (-1980000)) = 20000/2000000 = 0.01
	// If using unclamped: bitrate=15000, beyond=15000-2000000=-1985000
	//   s1 = 15000 / (15000 - (-1985000)) = 15000/2000000 = 0.0075
	//
	// Go mixes: bitrate=15000 (unclamped), beyond=-1980000 (from clamped)
	//   s1 = 15000 / (15000 - (-1980000)) = 15000/1995000 ≈ 0.007519

	unclampedBitrate := types.Ubps(15000)
	clampedBitrate := types.Ubps(20000)
	bitrateLow := types.Ubps(2000000)

	// What Go computes (mixed):
	goMixedBeyond := clampedBitrate - bitrateLow // -1980000
	goS1 := float64(unclampedBitrate) / float64(unclampedBitrate-goMixedBeyond)

	// What the spec intends with consistent clamped values:
	specConsistentBeyond := clampedBitrate - bitrateLow // -1980000
	specS1Clamped := float64(clampedBitrate) / float64(clampedBitrate-specConsistentBeyond)

	// What the spec intends with consistent unclamped values:
	specConsistentBeyondUnclamped := unclampedBitrate - bitrateLow // -1985000
	specS1Unclamped := float64(unclampedBitrate) / float64(unclampedBitrate-specConsistentBeyondUnclamped)

	t.Logf("Go mixed s1:         %f", goS1)
	t.Logf("Spec clamped s1:     %f", specS1Clamped)
	t.Logf("Spec unclamped s1:   %f", specS1Unclamped)

	// The Go result differs from BOTH consistent interpretations.
	// This documents the inconsistency.
	//
	// With consistent clamped values:
	//   s1 denominator = clampedBitRate - (clampedBitRate - BitrateLow) = BitrateLow
	//   s1 = clampedBitRate / BitrateLow
	//
	// With consistent unclamped values:
	//   s1 denominator = unclampedBitRate - (unclampedBitRate - BitrateLow) = BitrateLow
	//   s1 = unclampedBitRate / BitrateLow
	//
	// With mixed values (Go):
	//   s1 denominator = unclampedBitRate - (clampedBitRate - BitrateLow)
	//     = unclampedBitRate - clampedBitRate + BitrateLow
	//     ≠ BitrateLow  (when unclamped ≠ clamped)
	//
	// This means the Go code computes a WRONG denominator for s1 when
	// req.BitRate ≠ clampedVideoBitRate.

	testassert.InDelta(t, specS1Clamped, specS1Unclamped, 0.01,
		"both consistent interpretations should use BitrateLow as denominator")

	// Go's mixed computation gives a different denominator.
	// When unclamped != clamped, the Go result diverges from the spec.
	if math.Abs(float64(unclampedBitrate-clampedBitrate)) > 0 {
		testassert.Greater(t, math.Abs(specS1Clamped-goS1), 1e-6,
			"Go mixed computation should differ from consistent spec when unclamped != clamped")
	}
}

// ---------------------------------------------------------------------------
// Target 4: Resolution selection (getDesiredResolutionConfig)
// ---------------------------------------------------------------------------

func TestLeanSpec_GetDesiredResolutionConfig(t *testing.T) {
	res1080 := codec.Resolution{Width: 1920, Height: 1080}
	res720 := codec.Resolution{Width: 1280, Height: 720}
	res360 := codec.Resolution{Width: 640, Height: 360}

	resolutions := AutoBitRateResolutionAndBitRateConfigs{
		{Resolution: res1080, BitrateHigh: 8_000_000, BitrateLow: 3_000_000},
		{Resolution: res720, BitrateHigh: 4_000_000, BitrateLow: 1_000_000},
		{Resolution: res360, BitrateHigh: 1_500_000, BitrateLow: 200_000},
	}

	testCases := []struct {
		name    string
		bitrate types.Ubps
		curRes  codec.Resolution
		wantRes codec.Resolution
	}{
		// Lean: bitrate in [low, high] => some cur
		{
			name:    "within 1080p range: stay at 1080p",
			bitrate: 5_000_000,
			curRes:  res1080,
			wantRes: res1080,
		},
		{
			name:    "within 720p range: stay at 720p",
			bitrate: 2_000_000,
			curRes:  res720,
			wantRes: res720,
		},
		// Lean: bitrate < cur.bitrateLow => allowed.inRange(bitrate).best or allowed.worst
		{
			name:    "below 1080p low, 720p covers it: switch to 720p",
			bitrate: 2_000_000,
			curRes:  res1080,
			wantRes: res720,
		},
		// Lean: bitrate > cur.bitrateHigh => allowed.inRange(bitrate).worst or allowed.best
		{
			name:    "above 720p high, 1080p covers it: switch to 1080p (worst in range)",
			bitrate: 5_000_000,
			curRes:  res720,
			wantRes: res1080, // inRange(5M) = [1080p]; worst of that = 1080p
		},
		// Lean: bitrate below all ranges => allowed.worst
		{
			name:    "below all ranges: worst allowed (360p)",
			bitrate: 100,
			curRes:  res1080,
			wantRes: res360,
		},
		// Lean: bitrate above all ranges => allowed.best
		{
			name:    "above all ranges at 360p: best allowed (1080p)",
			bitrate: 100_000_000,
			curRes:  res360,
			wantRes: res1080,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			h := &AutoBitRateHandler[any]{
				AutoBitRateVideoConfig: AutoBitRateVideoConfig{
					ResolutionsAndBitRates: resolutions,
				},
			}
			got := h.getDesiredResolutionConfig(tc.bitrate, tc.curRes)
			testrequire.NotNil(t, got, "should return a resolution config")
			testassert.Equal(t, tc.wantRes, got.Resolution)
		})
	}
}

func TestLeanSpec_GetDesiredResolutionConfig_CurrentOutsideAllowed(t *testing.T) {
	res1080 := codec.Resolution{Width: 1920, Height: 1080}
	res720 := codec.Resolution{Width: 1280, Height: 720}
	res360 := codec.Resolution{Width: 640, Height: 360}

	resolutions := AutoBitRateResolutionAndBitRateConfigs{
		{Resolution: res1080, BitrateHigh: 8_000_000, BitrateLow: 3_000_000},
		{Resolution: res720, BitrateHigh: 4_000_000, BitrateLow: 1_000_000},
		{Resolution: res360, BitrateHigh: 1_500_000, BitrateLow: 200_000},
	}

	// Lean: if (allowed.find curW curH).isNone => allowed.inRange(bitrate).best or allowed.best
	h := &AutoBitRateHandler[any]{
		AutoBitRateVideoConfig: AutoBitRateVideoConfig{
			ResolutionsAndBitRates: resolutions,
			MaxResolution:          res720, // 1080p not allowed
		},
	}

	// At 1080p (not allowed), bitrate fits 720p
	got := h.getDesiredResolutionConfig(2_000_000, res1080)
	testrequire.NotNil(t, got)
	testassert.Equal(t, res720, got.Resolution,
		"should pick best allowed that covers the bitrate")

	// At 1080p (not allowed), very high bitrate (no match in range)
	got = h.getDesiredResolutionConfig(50_000_000, res1080)
	testrequire.NotNil(t, got)
	testassert.Equal(t, res720, got.Resolution,
		"should fall back to best allowed when no range match")
}

// ---------------------------------------------------------------------------
// Target 5: Bypass enable/disable thresholds
// ---------------------------------------------------------------------------

func TestLeanSpec_ShouldEnableBypass(t *testing.T) {
	testCases := []struct {
		name         string
		bitrate      types.Ubps
		inputBitRate types.Ubps
		want         bool
	}{
		{
			name:         "bitrate much higher than input: enable",
			bitrate:      12_000_000,
			inputBitRate: 8_000_000,
			want:         true, // 5*12M = 60M > 6*8M = 48M
		},
		{
			name:         "bitrate exactly at 1.2x: do not enable (not strictly greater)",
			bitrate:      12_000_000,
			inputBitRate: 10_000_000,
			want:         false, // 5*12M = 60M == 6*10M = 60M, not >
		},
		{
			name:         "bitrate barely above 1.2x: enable",
			bitrate:      12_000_001,
			inputBitRate: 10_000_000,
			want:         true, // 5*12000001 = 60000005 > 6*10000000 = 60000000
		},
		{
			name:         "bitrate below input: do not enable",
			bitrate:      5_000_000,
			inputBitRate: 8_000_000,
			want:         false,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			leanResult := leanShouldEnableBypass(tc.bitrate, tc.inputBitRate)
			testassert.Equal(t, tc.want, leanResult, "Lean reference")

			// Go production code (trySetVideoBitrate line 573)
			goResult := float64(tc.bitrate) > float64(tc.inputBitRate)*1.2
			testassert.Equal(t, tc.want, goResult, "Go production")
		})
	}
}

func TestLeanSpec_ShouldDisableBypass(t *testing.T) {
	testCases := []struct {
		name         string
		bitrate      types.Ubps
		inputBitRate types.Ubps
		want         bool
	}{
		{
			name:         "bitrate below input: disable",
			bitrate:      5_000_000,
			inputBitRate: 8_000_000,
			want:         true,
		},
		{
			name:         "bitrate equals input: do not disable",
			bitrate:      8_000_000,
			inputBitRate: 8_000_000,
			want:         false,
		},
		{
			name:         "bitrate above input: do not disable",
			bitrate:      10_000_000,
			inputBitRate: 8_000_000,
			want:         false,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			leanResult := leanShouldDisableBypass(tc.bitrate, tc.inputBitRate)
			testassert.Equal(t, tc.want, leanResult, "Lean reference")

			// Go production code (trySetVideoBitrate line 567)
			goResult := tc.bitrate < tc.inputBitRate
			testassert.Equal(t, tc.want, goResult, "Go production")
		})
	}
}

// ---------------------------------------------------------------------------
// Target 5: Bypass enable exact threshold (Lean 5*bitrate > 6*inputBitRate
//           vs Go float64(bitrate) > float64(inputBitRate)*1.2)
// ---------------------------------------------------------------------------

func TestLeanSpec_BypassEnableThreshold_FloatPrecision(t *testing.T) {
	// Lean uses integer arithmetic: 5 * bitrate > 6 * inputBitRate
	// Go uses float64: bitrate > inputBitRate * 1.2
	//
	// These are mathematically equivalent. But for values where
	// inputBitRate * 1.2 is not exactly representable in float64,
	// the Go comparison might differ from the Lean integer comparison.
	//
	// In practice, bitrates are large integers stored as float64.
	// float64 has 53-bit mantissa, so integers up to 2^53 are exact.
	// Typical bitrates (< 100 Mbps = 10^8) are far below 2^53 ≈ 9 * 10^15.
	// So integer-valued float64 arithmetic is exact for practical bitrates.

	// Test edge case: inputBitRate where 1.2 * inputBitRate is not integer
	inputBitRate := types.Ubps(10_000_001)
	threshold := inputBitRate * 1.2 // 12000001.2

	// Lean: 5 * 12000002 = 60000010 > 6 * 10000001 = 60000006 → true
	bitrate := types.Ubps(12_000_002)
	leanResult := 5*int64(bitrate) > 6*int64(inputBitRate)
	goResult := float64(bitrate) > float64(inputBitRate)*1.2

	testassert.Equal(t, leanResult, goResult,
		"Lean (5*%d > 6*%d = %v) vs Go (%f > %f = %v)",
		int64(bitrate), int64(inputBitRate), leanResult,
		float64(bitrate), threshold, goResult)

	// Lean: 5 * 12000001 = 60000005 < 6 * 10000001 = 60000006 → false
	bitrate = types.Ubps(12_000_001)
	leanResult = 5*int64(bitrate) > 6*int64(inputBitRate)
	goResult = float64(bitrate) > float64(inputBitRate)*1.2

	testassert.Equal(t, leanResult, goResult,
		"boundary: Lean (5*%d > 6*%d = %v) vs Go (%f > %f = %v)",
		int64(bitrate), int64(inputBitRate), leanResult,
		float64(bitrate), threshold, goResult)
}
