// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: kernel.proto

package kernel

import (
	context "context"
	libav "github.com/xaionaro-go/avpipeline/protobuf/libav"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Kernel_SendInput_FullMethodName                      = "/kernel.Kernel/SendInput"
	Kernel_String_FullMethodName                         = "/kernel.Kernel/String"
	Kernel_Close_FullMethodName                          = "/kernel.Kernel/Close"
	Kernel_CloseChan_FullMethodName                      = "/kernel.Kernel/CloseChan"
	Kernel_GeneratePackets_FullMethodName                = "/kernel.Kernel/GeneratePackets"
	Kernel_GenerateFrame_FullMethodName                  = "/kernel.Kernel/GenerateFrame"
	Kernel_GetOutputFormatContext_FullMethodName         = "/kernel.Kernel/GetOutputFormatContext"
	Kernel_GetInputFormatContext_FullMethodName          = "/kernel.Kernel/GetInputFormatContext"
	Kernel_NotifyAboutPacketFormatContext_FullMethodName = "/kernel.Kernel/NotifyAboutPacketFormatContext"
)

// KernelClient is the client API for Kernel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KernelClient interface {
	SendInput(ctx context.Context, in *SendInputRequest, opts ...grpc.CallOption) (*SendInputReply, error)
	String(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.StringValue, error)
	Close(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CloseChan(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Kernel_CloseChanClient, error)
	GeneratePackets(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Kernel_GeneratePacketsClient, error)
	GenerateFrame(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Kernel_GenerateFrameClient, error)
	GetOutputFormatContext(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetOutputFormatContextReply, error)
	GetInputFormatContext(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetInputFormatContextReply, error)
	NotifyAboutPacketFormatContext(ctx context.Context, in *NotifyAboutPacketFormatContextRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type kernelClient struct {
	cc grpc.ClientConnInterface
}

func NewKernelClient(cc grpc.ClientConnInterface) KernelClient {
	return &kernelClient{cc}
}

func (c *kernelClient) SendInput(ctx context.Context, in *SendInputRequest, opts ...grpc.CallOption) (*SendInputReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendInputReply)
	err := c.cc.Invoke(ctx, Kernel_SendInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelClient) String(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.StringValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.StringValue)
	err := c.cc.Invoke(ctx, Kernel_String_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelClient) Close(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Kernel_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelClient) CloseChan(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Kernel_CloseChanClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kernel_ServiceDesc.Streams[0], Kernel_CloseChan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &kernelCloseChanClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Kernel_CloseChanClient interface {
	Recv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type kernelCloseChanClient struct {
	grpc.ClientStream
}

func (x *kernelCloseChanClient) Recv() (*emptypb.Empty, error) {
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kernelClient) GeneratePackets(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Kernel_GeneratePacketsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kernel_ServiceDesc.Streams[1], Kernel_GeneratePackets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &kernelGeneratePacketsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Kernel_GeneratePacketsClient interface {
	Recv() (*libav.Packet, error)
	grpc.ClientStream
}

type kernelGeneratePacketsClient struct {
	grpc.ClientStream
}

func (x *kernelGeneratePacketsClient) Recv() (*libav.Packet, error) {
	m := new(libav.Packet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kernelClient) GenerateFrame(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Kernel_GenerateFrameClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kernel_ServiceDesc.Streams[2], Kernel_GenerateFrame_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &kernelGenerateFrameClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Kernel_GenerateFrameClient interface {
	Recv() (*libav.Frame, error)
	grpc.ClientStream
}

type kernelGenerateFrameClient struct {
	grpc.ClientStream
}

func (x *kernelGenerateFrameClient) Recv() (*libav.Frame, error) {
	m := new(libav.Frame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kernelClient) GetOutputFormatContext(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetOutputFormatContextReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOutputFormatContextReply)
	err := c.cc.Invoke(ctx, Kernel_GetOutputFormatContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelClient) GetInputFormatContext(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetInputFormatContextReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInputFormatContextReply)
	err := c.cc.Invoke(ctx, Kernel_GetInputFormatContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelClient) NotifyAboutPacketFormatContext(ctx context.Context, in *NotifyAboutPacketFormatContextRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Kernel_NotifyAboutPacketFormatContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KernelServer is the server API for Kernel service.
// All implementations must embed UnimplementedKernelServer
// for forward compatibility
type KernelServer interface {
	SendInput(context.Context, *SendInputRequest) (*SendInputReply, error)
	String(context.Context, *emptypb.Empty) (*wrapperspb.StringValue, error)
	Close(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	CloseChan(*emptypb.Empty, Kernel_CloseChanServer) error
	GeneratePackets(*emptypb.Empty, Kernel_GeneratePacketsServer) error
	GenerateFrame(*emptypb.Empty, Kernel_GenerateFrameServer) error
	GetOutputFormatContext(context.Context, *emptypb.Empty) (*GetOutputFormatContextReply, error)
	GetInputFormatContext(context.Context, *emptypb.Empty) (*GetInputFormatContextReply, error)
	NotifyAboutPacketFormatContext(context.Context, *NotifyAboutPacketFormatContextRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedKernelServer()
}

// UnimplementedKernelServer must be embedded to have forward compatible implementations.
type UnimplementedKernelServer struct {
}

func (UnimplementedKernelServer) SendInput(context.Context, *SendInputRequest) (*SendInputReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendInput not implemented")
}
func (UnimplementedKernelServer) String(context.Context, *emptypb.Empty) (*wrapperspb.StringValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method String not implemented")
}
func (UnimplementedKernelServer) Close(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedKernelServer) CloseChan(*emptypb.Empty, Kernel_CloseChanServer) error {
	return status.Errorf(codes.Unimplemented, "method CloseChan not implemented")
}
func (UnimplementedKernelServer) GeneratePackets(*emptypb.Empty, Kernel_GeneratePacketsServer) error {
	return status.Errorf(codes.Unimplemented, "method GeneratePackets not implemented")
}
func (UnimplementedKernelServer) GenerateFrame(*emptypb.Empty, Kernel_GenerateFrameServer) error {
	return status.Errorf(codes.Unimplemented, "method GenerateFrame not implemented")
}
func (UnimplementedKernelServer) GetOutputFormatContext(context.Context, *emptypb.Empty) (*GetOutputFormatContextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOutputFormatContext not implemented")
}
func (UnimplementedKernelServer) GetInputFormatContext(context.Context, *emptypb.Empty) (*GetInputFormatContextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInputFormatContext not implemented")
}
func (UnimplementedKernelServer) NotifyAboutPacketFormatContext(context.Context, *NotifyAboutPacketFormatContextRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyAboutPacketFormatContext not implemented")
}
func (UnimplementedKernelServer) mustEmbedUnimplementedKernelServer() {}

// UnsafeKernelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KernelServer will
// result in compilation errors.
type UnsafeKernelServer interface {
	mustEmbedUnimplementedKernelServer()
}

func RegisterKernelServer(s grpc.ServiceRegistrar, srv KernelServer) {
	s.RegisterService(&Kernel_ServiceDesc, srv)
}

func _Kernel_SendInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServer).SendInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kernel_SendInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServer).SendInput(ctx, req.(*SendInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kernel_String_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServer).String(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kernel_String_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServer).String(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kernel_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kernel_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServer).Close(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kernel_CloseChan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelServer).CloseChan(m, &kernelCloseChanServer{ServerStream: stream})
}

type Kernel_CloseChanServer interface {
	Send(*emptypb.Empty) error
	grpc.ServerStream
}

type kernelCloseChanServer struct {
	grpc.ServerStream
}

func (x *kernelCloseChanServer) Send(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func _Kernel_GeneratePackets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelServer).GeneratePackets(m, &kernelGeneratePacketsServer{ServerStream: stream})
}

type Kernel_GeneratePacketsServer interface {
	Send(*libav.Packet) error
	grpc.ServerStream
}

type kernelGeneratePacketsServer struct {
	grpc.ServerStream
}

func (x *kernelGeneratePacketsServer) Send(m *libav.Packet) error {
	return x.ServerStream.SendMsg(m)
}

func _Kernel_GenerateFrame_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelServer).GenerateFrame(m, &kernelGenerateFrameServer{ServerStream: stream})
}

type Kernel_GenerateFrameServer interface {
	Send(*libav.Frame) error
	grpc.ServerStream
}

type kernelGenerateFrameServer struct {
	grpc.ServerStream
}

func (x *kernelGenerateFrameServer) Send(m *libav.Frame) error {
	return x.ServerStream.SendMsg(m)
}

func _Kernel_GetOutputFormatContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServer).GetOutputFormatContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kernel_GetOutputFormatContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServer).GetOutputFormatContext(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kernel_GetInputFormatContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServer).GetInputFormatContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kernel_GetInputFormatContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServer).GetInputFormatContext(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kernel_NotifyAboutPacketFormatContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyAboutPacketFormatContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServer).NotifyAboutPacketFormatContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kernel_NotifyAboutPacketFormatContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServer).NotifyAboutPacketFormatContext(ctx, req.(*NotifyAboutPacketFormatContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Kernel_ServiceDesc is the grpc.ServiceDesc for Kernel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kernel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kernel.Kernel",
	HandlerType: (*KernelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendInput",
			Handler:    _Kernel_SendInput_Handler,
		},
		{
			MethodName: "String",
			Handler:    _Kernel_String_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Kernel_Close_Handler,
		},
		{
			MethodName: "GetOutputFormatContext",
			Handler:    _Kernel_GetOutputFormatContext_Handler,
		},
		{
			MethodName: "GetInputFormatContext",
			Handler:    _Kernel_GetInputFormatContext_Handler,
		},
		{
			MethodName: "NotifyAboutPacketFormatContext",
			Handler:    _Kernel_NotifyAboutPacketFormatContext_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CloseChan",
			Handler:       _Kernel_CloseChan_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GeneratePackets",
			Handler:       _Kernel_GeneratePackets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GenerateFrame",
			Handler:       _Kernel_GenerateFrame_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kernel.proto",
}
