// Code generated by GitHub Copilot.
package kernel

import (
	"context"
	"testing"

	"github.com/asticode/go-astiav"
	"github.com/stretchr/testify/require"
)

func TestFixVideoGapDuplicateNextFrame(t *testing.T) {
	ctx := context.Background()

	tests := []struct {
		name             string
		gapStart         int64
		inputPTS         int64
		originalDuration int64
		expectedFrames   []struct {
			pts      int64
			duration int64
		}
	}{
		{
			name:             "Exact Multiple Gap",
			gapStart:         70,
			inputPTS:         100,
			originalDuration: 10,
			expectedFrames: []struct {
				pts      int64
				duration int64
			}{
				{pts: 70, duration: 10},
				{pts: 80, duration: 10},
				{pts: 90, duration: 10},
				{pts: 100, duration: 10},
			},
		},
		{
			name:             "Non-Multiple Gap (Need Extension)",
			gapStart:         20,
			inputPTS:         100,
			originalDuration: 30,
			expectedFrames: []struct {
				pts      int64
				duration int64
			}{
				{pts: 20, duration: 30},
				{pts: 50, duration: 30},
				{pts: 80, duration: 20}, // Extended to reach 100
				{pts: 100, duration: 30},
			},
		},
		{
			name:             "Gap smaller than duration",
			gapStart:         85,
			inputPTS:         100,
			originalDuration: 30,
			expectedFrames: []struct {
				pts      int64
				duration int64
			}{
				{pts: 85, duration: 15}, // Extended to reach 100
				{pts: 100, duration: 30},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			se := &streamEncoder{
				EncoderConfig: &EncoderConfig{
					VideoGapsStrategy: VideoGapsStrategyDuplicateNextFrame,
				},
			}

			inputFrame := astiav.AllocFrame()
			defer inputFrame.Free()
			inputFrame.SetPts(tt.inputPTS)
			inputFrame.SetDuration(tt.originalDuration)

			result := se.fixVideoGapDuplicateNextFrame(ctx, inputFrame, tt.gapStart)

			require.Equal(t, len(tt.expectedFrames), len(result))
			for i, expected := range tt.expectedFrames {
				require.Equal(t, expected.pts, result[i].Pts(), "Frame %d PTS mismatch", i)
				require.Equal(t, expected.duration, result[i].Duration(), "Frame %d Duration mismatch", i)
			}
		})
	}
}

func TestFixVideoGapIfNeeded(t *testing.T) {
	ctx := context.Background()

	t.Run("Sequential Frames No Gaps", func(t *testing.T) {
		se := &streamEncoder{
			EncoderConfig: &EncoderConfig{
				VideoGapsStrategy: VideoGapsStrategyDuplicateNextFrame,
			},
		}

		f1 := astiav.AllocFrame()
		defer f1.Free()
		f1.SetPts(0)
		f1.SetDuration(10)

		f2 := astiav.AllocFrame()
		defer f2.Free()
		f2.SetPts(10)
		f2.SetDuration(10)

		result := se.fixVideoGapIfNeeded(ctx, []*astiav.Frame{f1, f2})
		require.Equal(t, 2, len(result))
		require.Equal(t, int64(0), result[0].Pts())
		require.Equal(t, int64(10), result[1].Pts())
	})

	t.Run("Gap Across Calls", func(t *testing.T) {
		se := &streamEncoder{
			EncoderConfig: &EncoderConfig{
				VideoGapsStrategy: VideoGapsStrategyDuplicateNextFrame,
			},
		}

		f1 := astiav.AllocFrame()
		defer f1.Free()
		f1.SetPts(0)
		f1.SetDuration(10)

		// First call
		result1 := se.fixVideoGapIfNeeded(ctx, []*astiav.Frame{f1})
		require.Equal(t, 1, len(result1))
		require.Equal(t, int64(0), result1[0].Pts())
		require.Equal(t, int64(10), se.NextExpectedPTS)

		// Second call with gap
		f2 := astiav.AllocFrame()
		defer f2.Free()
		f2.SetPts(25)
		f2.SetDuration(10)

		result2 := se.fixVideoGapIfNeeded(ctx, []*astiav.Frame{f2})
		// Expected: 2 duplicates (PTS 10/10, PTS 20/5) + 1 original (PTS 25/10)
		require.Equal(t, 3, len(result2))
		require.Equal(t, int64(10), result2[0].Pts())
		require.Equal(t, int64(10), result2[0].Duration())
		require.Equal(t, int64(20), result2[1].Pts())
		require.Equal(t, int64(5), result2[1].Duration())
		require.Equal(t, int64(25), result2[2].Pts())
		require.Equal(t, int64(10), result2[2].Duration())
	})

	t.Run("Strategy ExtendNextFrame", func(t *testing.T) {
		se := &streamEncoder{
			EncoderConfig: &EncoderConfig{
				VideoGapsStrategy: VideoGapsStrategyExtendNextFrame,
			},
		}

		f1 := astiav.AllocFrame()
		defer f1.Free()
		f1.SetPts(0)
		f1.SetDuration(10)

		se.fixVideoGapIfNeeded(ctx, []*astiav.Frame{f1})

		f2 := astiav.AllocFrame()
		defer f2.Free()
		f2.SetPts(30)
		f2.SetDuration(10)

		result := se.fixVideoGapIfNeeded(ctx, []*astiav.Frame{f2})
		require.Equal(t, 1, len(result))
		require.Equal(t, int64(10), result[0].Pts())
		require.Equal(t, int64(30), result[0].Duration())
	})
}
