// Code generated by Agent.
package kernel

import (
	"context"
	"testing"
	"time"

	"github.com/asticode/go-astiav"
	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/avpipeline/codec"
)

func TestFixVideoGapAddBlankFrames(t *testing.T) {
	ctx := context.Background()

	se := &streamEncoder{}
	inputFrame := astiav.AllocFrame()
	defer inputFrame.Free()
	inputFrame.SetPts(100)
	inputFrame.SetDuration(10)
	inputFrame.SetWidth(100)
	inputFrame.SetHeight(100)
	inputFrame.SetPixelFormat(astiav.PixelFormatYuv420P)

	// Gap from 70 to 100 with duration 10
	result := se.fixVideoGapAddBlankFrames(ctx, inputFrame, 70)

	require.Equal(t, 4, len(result))
	require.Equal(t, int64(70), result[0].Pts())
	require.Equal(t, int64(10), result[0].Duration())
	require.Equal(t, int64(80), result[1].Pts())
	require.Equal(t, int64(10), result[1].Duration())
	require.Equal(t, int64(90), result[2].Pts())
	require.Equal(t, int64(10), result[2].Duration())
	require.Equal(t, int64(100), result[3].Pts())
	require.Equal(t, int64(10), result[3].Duration())
}

func TestFixAudioGapAddSilence(t *testing.T) {
	ctx := context.Background()

	se := &streamEncoder{}
	inputFrame := astiav.AllocFrame()
	defer inputFrame.Free()
	inputFrame.SetSampleFormat(astiav.SampleFormatS16)
	inputFrame.SetSampleRate(44100)
	inputFrame.SetChannelLayout(astiav.ChannelLayoutStereo)
	inputFrame.SetNbSamples(1024)
	inputFrame.SetPts(2048)
	inputFrame.SetDuration(1024)

	// Gap from 1024 to 2048
	result := se.fixAudioGapAddSilence(ctx, inputFrame, 1024)

	require.Equal(t, 2, len(result))
	require.Equal(t, int64(1024), result[0].Pts())
	require.Equal(t, int64(1024), result[0].Duration())
	require.Equal(t, int64(1024), int64(result[0].NbSamples()))
	require.Equal(t, int64(2048), result[1].Pts())
}

func TestFixAudioGapRepeat(t *testing.T) {
	ctx := context.Background()

	se := &streamEncoder{
		EncoderConfig: &EncoderConfig{
			AudioGapsStrategy: AudioGapsStrategyRepeat,
		},
	}

	lastFrame := astiav.AllocFrame()
	lastFrame.SetSampleFormat(astiav.SampleFormatS16)
	lastFrame.SetSampleRate(44100)
	lastFrame.SetChannelLayout(astiav.ChannelLayoutStereo)
	lastFrame.SetNbSamples(1024)
	lastFrame.SetPts(0)
	lastFrame.SetDuration(1024)
	err := lastFrame.AllocBuffer(0)
	require.NoError(t, err)

	se.LastAudioFrame = lastFrame

	inputFrame := astiav.AllocFrame()
	inputFrame.SetSampleFormat(astiav.SampleFormatS16)
	inputFrame.SetSampleRate(44100)
	inputFrame.SetChannelLayout(astiav.ChannelLayoutStereo)
	inputFrame.SetNbSamples(1024)
	inputFrame.SetPts(2048)
	inputFrame.SetDuration(1024)
	err = inputFrame.AllocBuffer(0)
	require.NoError(t, err)

	// Gap from 1024 to 2048
	result := se.fixAudioGapRepeat(ctx, inputFrame, 1024)

	require.Equal(t, 2, len(result))
	require.Equal(t, int64(1024), result[0].Pts())
	require.Equal(t, int64(1024), result[0].Duration())
	require.Equal(t, int64(2048), result[1].Pts())
}

type mockEncoder struct {
	codec.Encoder
	ctx *astiav.CodecContext
}

func (m *mockEncoder) CodecContext() *astiav.CodecContext { return m.ctx }

func TestFixVideoGapMaxGap(t *testing.T) {
	ctx := context.Background()

	cc := astiav.AllocCodecContext(nil)
	defer cc.Free()
	cc.SetTimeBase(astiav.NewRational(1, 1000)) // 1ms units

	se := &streamEncoder{
		EncoderConfig: &EncoderConfig{
			VideoGapsStrategy:   VideoGapsStrategyDuplicateNextFrame,
			VideoMaxGapDuration: 50 * time.Millisecond,
		},
		Encoder:            &mockEncoder{ctx: cc},
		NextExpectedPTS:    10,
		NextExpectedPTSSet: true,
	}

	inputFrame := astiav.AllocFrame()
	defer inputFrame.Free()
	inputFrame.SetPts(100) // Gap of 90ms > 50ms
	inputFrame.SetDuration(10)

	result := se.fixVideoGapIfNeededForOneFrame(ctx, inputFrame)

	require.Equal(t, 1, len(result))
	require.Equal(t, int64(100), result[0].Pts())
}

func TestFixAudioGapMaxGap(t *testing.T) {
	ctx := context.Background()

	cc := astiav.AllocCodecContext(nil)
	defer cc.Free()
	cc.SetTimeBase(astiav.NewRational(1, 1000)) // 1ms units

	se := &streamEncoder{
		EncoderConfig: &EncoderConfig{
			AudioGapsStrategy:   AudioGapsStrategyAddSilence,
			AudioMaxGapDuration: 50 * time.Millisecond,
		},
		Encoder:            &mockEncoder{ctx: cc},
		NextExpectedPTS:    10,
		NextExpectedPTSSet: true,
	}

	inputFrame := astiav.AllocFrame()
	defer inputFrame.Free()
	inputFrame.SetPts(100) // Gap of 90ms > 50ms
	inputFrame.SetDuration(10)
	inputFrame.SetSampleFormat(astiav.SampleFormatS16)
	inputFrame.SetSampleRate(1000)
	inputFrame.SetChannelLayout(astiav.ChannelLayoutMono)
	inputFrame.SetNbSamples(10)

	result := se.fixAudioGapIfNeededForOneFrame(ctx, inputFrame)

	require.Equal(t, 1, len(result))
	require.Equal(t, int64(100), result[0].Pts())
}
