//go:build with_cv
// +build with_cv

// Tests auto-generated by AI agent.
package kernel

import (
	"context"
	"image"
	"sync/atomic"
	"testing"

	"github.com/asticode/go-astiav"
	testifyassert "github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/avpipeline/frame"
	"github.com/xaionaro-go/avpipeline/kernel/cascadedata"
	"github.com/xaionaro-go/avpipeline/packetorframe"
)

func newTestPrivacyBlur(t *testing.T) *PrivacyBlur {
	t.Helper()
	pb, err := NewPrivacyBlur(PrivacyBlurConfig{
		Classifiers: []ClassifierConfig{
			{
				Name:         "face",
				XML:          cascadedata.FaceFrontalDefault,
				ScaleFactor:  1.1,
				MinNeighbors: 3,
				MinSize:      image.Pt(30, 30),
			},
		},
		BlurRadius: 10,
	})
	require.NoError(t, err)
	return pb
}

func newTestVideoFrame(t *testing.T, w, h int) *astiav.Frame {
	t.Helper()
	f := astiav.AllocFrame()
	f.SetWidth(w)
	f.SetHeight(h)
	f.SetPixelFormat(astiav.PixelFormatYuv420P)
	require.NoError(t, f.AllocBuffer(32))
	return f
}

func newTestVideoInput(t *testing.T, w, h int) packetorframe.InputUnion {
	t.Helper()
	f := newTestVideoFrame(t, w, h)
	codecParams := astiav.AllocCodecParameters()
	codecParams.SetMediaType(astiav.MediaTypeVideo)
	codecParams.SetWidth(w)
	codecParams.SetHeight(h)
	codecParams.SetPixelFormat(astiav.PixelFormatYuv420P)
	return packetorframe.InputUnion{
		Frame: &frame.Input{
			Frame: f,
			StreamInfo: &frame.StreamInfo{
				StreamIndex:     0,
				CodecParameters: codecParams,
			},
		},
	}
}

func TestPrivacyBlur_Passthrough(t *testing.T) {
	pb := newTestPrivacyBlur(t)
	defer pb.Close(context.Background())

	enabled := &atomic.Bool{}
	enabled.Store(false)
	pb.Enabled = enabled

	ctx := context.Background()
	input := newTestVideoInput(t, 320, 240)
	defer input.Frame.Frame.Free()
	defer input.Frame.CodecParameters.Free()
	outputCh := make(chan packetorframe.OutputUnion, 1)

	err := pb.SendInput(ctx, input, outputCh)
	require.NoError(t, err)
	require.Len(t, outputCh, 1)

	out := <-outputCh
	require.NotNil(t, out.Frame)
}

func TestPrivacyBlur_EnabledNil(t *testing.T) {
	pb := newTestPrivacyBlur(t)
	defer pb.Close(context.Background())
	// Enabled is nil = always on (should not panic).

	ctx := context.Background()
	input := newTestVideoInput(t, 320, 240)
	defer input.Frame.Frame.Free()
	defer input.Frame.CodecParameters.Free()
	outputCh := make(chan packetorframe.OutputUnion, 1)

	err := pb.SendInput(ctx, input, outputCh)
	require.NoError(t, err)
	require.Len(t, outputCh, 1)

	out := <-outputCh
	require.NotNil(t, out.Frame)
	testifyassert.Equal(t, 320, out.Frame.Width())
	testifyassert.Equal(t, 240, out.Frame.Height())
}

func TestPrivacyBlur_RuntimeToggle(t *testing.T) {
	pb := newTestPrivacyBlur(t)
	defer pb.Close(context.Background())

	enabled := &atomic.Bool{}
	enabled.Store(true)
	pb.Enabled = enabled

	ctx := context.Background()

	// Frame 1: enabled.
	input1 := newTestVideoInput(t, 320, 240)
	defer input1.Frame.Frame.Free()
	defer input1.Frame.CodecParameters.Free()
	outputCh := make(chan packetorframe.OutputUnion, 1)
	err := pb.SendInput(ctx, input1, outputCh)
	require.NoError(t, err)
	require.Len(t, outputCh, 1)
	<-outputCh

	// Disable.
	enabled.Store(false)

	// Frame 2: disabled (passthrough).
	input2 := newTestVideoInput(t, 320, 240)
	defer input2.Frame.Frame.Free()
	defer input2.Frame.CodecParameters.Free()
	err = pb.SendInput(ctx, input2, outputCh)
	require.NoError(t, err)
	require.Len(t, outputCh, 1)
	<-outputCh

	// Re-enable.
	enabled.Store(true)

	// Frame 3: enabled again.
	input3 := newTestVideoInput(t, 320, 240)
	defer input3.Frame.Frame.Free()
	defer input3.Frame.CodecParameters.Free()
	err = pb.SendInput(ctx, input3, outputCh)
	require.NoError(t, err)
	require.Len(t, outputCh, 1)
}

func TestPrivacyBlur_BlurRadiusChange(t *testing.T) {
	pb := newTestPrivacyBlur(t)
	defer pb.Close(context.Background())

	ctx := context.Background()

	// Process with initial radius.
	input1 := newTestVideoInput(t, 320, 240)
	defer input1.Frame.Frame.Free()
	defer input1.Frame.CodecParameters.Free()
	outputCh := make(chan packetorframe.OutputUnion, 1)
	err := pb.SendInput(ctx, input1, outputCh)
	require.NoError(t, err)
	<-outputCh

	// Change blur radius.
	pb.BlurRadius.Store(25)

	// Process again with new radius.
	input2 := newTestVideoInput(t, 320, 240)
	defer input2.Frame.Frame.Free()
	defer input2.Frame.CodecParameters.Free()
	err = pb.SendInput(ctx, input2, outputCh)
	require.NoError(t, err)
	require.Len(t, outputCh, 1)
}

func TestPrivacyBlur_PixelateMode(t *testing.T) {
	pb := newTestPrivacyBlur(t)
	defer pb.Close(context.Background())

	pb.PixelateBlockSize.Store(10)
	pb.BlurRadius.Store(0)

	ctx := context.Background()
	input := newTestVideoInput(t, 320, 240)
	defer input.Frame.Frame.Free()
	defer input.Frame.CodecParameters.Free()
	outputCh := make(chan packetorframe.OutputUnion, 1)

	err := pb.SendInput(ctx, input, outputCh)
	require.NoError(t, err)
	require.Len(t, outputCh, 1)
}

func TestPrivacyBlur_NonVideoPassthrough(t *testing.T) {
	pb := newTestPrivacyBlur(t)
	defer pb.Close(context.Background())

	ctx := context.Background()

	// Create an audio frame input.
	f := astiav.AllocFrame()
	defer f.Free()
	f.SetSampleRate(44100)
	f.SetSampleFormat(astiav.SampleFormatFltp)
	f.SetChannelLayout(astiav.ChannelLayoutMono)
	f.SetNbSamples(1024)
	require.NoError(t, f.AllocBuffer(0))

	codecParams := astiav.AllocCodecParameters()
	defer codecParams.Free()
	codecParams.SetMediaType(astiav.MediaTypeAudio)

	input := packetorframe.InputUnion{
		Frame: &frame.Input{
			Frame: f,
			StreamInfo: &frame.StreamInfo{
				StreamIndex:     1,
				CodecParameters: codecParams,
			},
		},
	}

	outputCh := make(chan packetorframe.OutputUnion, 1)
	err := pb.SendInput(ctx, input, outputCh)
	require.NoError(t, err)
	require.Len(t, outputCh, 1)
}

func TestPrivacyBlur_PacketPassthrough(t *testing.T) {
	pb := newTestPrivacyBlur(t)
	defer pb.Close(context.Background())

	ctx := context.Background()

	// Packet input should passthrough.
	input := packetorframe.InputUnion{}
	outputCh := make(chan packetorframe.OutputUnion, 1)
	err := pb.SendInput(ctx, input, outputCh)
	require.NoError(t, err)
	require.Len(t, outputCh, 1)
}

func TestPrivacyBlur_Close(t *testing.T) {
	pb := newTestPrivacyBlur(t)
	ctx := context.Background()
	testifyassert.NoError(t, pb.Close(ctx))
	// Idempotent.
	testifyassert.NoError(t, pb.Close(ctx))
}

func TestPrivacyBlur_String(t *testing.T) {
	pb := newTestPrivacyBlur(t)
	defer pb.Close(context.Background())

	s := pb.String()
	testifyassert.Contains(t, s, "PrivacyBlur")
	testifyassert.Contains(t, s, "face")
}

func TestPrivacyBlur_StringMultipleClassifiers(t *testing.T) {
	pb, err := NewPrivacyBlur(PrivacyBlurConfig{
		Classifiers: []ClassifierConfig{
			{Name: "face", XML: cascadedata.FaceFrontalDefault},
			{Name: "plate", XML: cascadedata.PlateRussian},
		},
		BlurRadius: 10,
	})
	require.NoError(t, err)
	defer pb.Close(context.Background())

	s := pb.String()
	testifyassert.Contains(t, s, "face")
	testifyassert.Contains(t, s, "plate")
}

func TestPrivacyBlur_Generate(t *testing.T) {
	pb := newTestPrivacyBlur(t)
	defer pb.Close(context.Background())

	err := pb.Generate(context.Background(), nil)
	testifyassert.NoError(t, err)
}

func TestNewPrivacyBlur_NoClassifiers(t *testing.T) {
	_, err := NewPrivacyBlur(PrivacyBlurConfig{})
	testifyassert.Error(t, err)
	testifyassert.Contains(t, err.Error(), "at least one classifier")
}

func TestNewPrivacyBlur_InvalidXML(t *testing.T) {
	_, err := NewPrivacyBlur(PrivacyBlurConfig{
		Classifiers: []ClassifierConfig{
			{Name: "bad", XML: []byte("not valid xml")},
		},
	})
	testifyassert.Error(t, err)
}

func TestPrivacyBlur_DefaultBlurRadius(t *testing.T) {
	pb, err := NewPrivacyBlur(PrivacyBlurConfig{
		Classifiers: []ClassifierConfig{
			{Name: "face", XML: cascadedata.FaceFrontalDefault},
		},
	})
	require.NoError(t, err)
	defer pb.Close(context.Background())

	// Default blur radius should be 15.
	testifyassert.Equal(t, float64(15), pb.BlurRadius.Load())
}
