// barrier_test.go exercises the real barrierstategetter.Switch and prints
// results in the same format as the Lean DiffTest.Pipeline.Barrier harness.
//
// Test cases are generated by this file (agent-generated test).
package difftestgo

import (
	"context"
	"fmt"
	"math"
	"testing"

	"github.com/asticode/go-astiav"
	barrierstategetter "github.com/xaionaro-go/avpipeline/kernel/barrier/stategetter"
	barriertypes "github.com/xaionaro-go/avpipeline/kernel/barrier/types"
	"github.com/xaionaro-go/avpipeline/packet"
	"github.com/xaionaro-go/avpipeline/packetorframe"
	packetorframecondition "github.com/xaionaro-go/avpipeline/packetorframe/condition"
	packetorframetypes "github.com/xaionaro-go/avpipeline/packetorframe/types"
)

// switchTestCase mirrors a single line of the Lean DiffTest input:
//
//	switch <currentValue> <nextValue_or_none> <outputID> <mediaType> <isKeyFrame> <keepUnlessName>
type switchTestCase struct {
	name         string
	currentValue int32
	nextValue    int32  // math.MinInt32 means "none" (no pending switch)
	outputID     int32
	mediaType    string // "video", "audio", "subtitle", "data"
	isKeyFrame   bool
	keepUnless   string // "keepunless", "always", "never"
	expected     string // "pass", "drop", "block"
}

// buildKeepUnlessCond constructs the packetorframecondition.Condition that
// corresponds to the named keepUnless variant used in the Lean spec.
//
//   - "keepunless" => And{MediaType(video), Or{IsKeyFrame(true)}}
//     (This is standardKeepUnless false: video AND (keyframe OR never).)
//   - "always" => Static(true)
//   - "never"  => Static(false)
func buildKeepUnlessCond(name string) packetorframecondition.Condition {
	switch name {
	case "keepunless":
		return packetorframecondition.And{
			packetorframecondition.MediaType(astiav.MediaTypeVideo),
			packetorframecondition.Or{packetorframecondition.IsKeyFrame(true)},
		}
	case "always":
		return packetorframecondition.Static(true)
	case "never":
		return packetorframecondition.Static(false)
	default:
		panic(fmt.Sprintf("unknown keepUnless name: %q", name))
	}
}

// mediaTypeToAstiav maps a string media type to the astiav constant.
func mediaTypeToAstiav(mt string) astiav.MediaType {
	switch mt {
	case "video":
		return astiav.MediaTypeVideo
	case "audio":
		return astiav.MediaTypeAudio
	case "subtitle":
		return astiav.MediaTypeSubtitle
	case "data":
		return astiav.MediaTypeData
	default:
		panic(fmt.Sprintf("unknown media type: %q", mt))
	}
}

// stateToString maps a barrier State to the Lean DiffTest result string.
func stateToString(s barriertypes.State) string {
	switch s {
	case barriertypes.StatePass:
		return "pass"
	case barriertypes.StateDrop:
		return "drop"
	case barriertypes.StateBlock:
		return "block"
	default:
		return fmt.Sprintf("unknown_%d", int(s))
	}
}

// buildInputUnion constructs a packetorframe.InputUnion with the specified
// media type and keyframe flag.  The returned cleanup function frees the
// underlying astiav.Packet.
func buildInputUnion(t *testing.T, mediaType string, isKeyFrame bool) packetorframe.InputUnion {
	t.Helper()

	pkt := astiav.AllocPacket()
	t.Cleanup(pkt.Free)

	if isKeyFrame {
		pkt.SetFlags(astiav.PacketFlags(0).Add(astiav.PacketFlagKey))
	}

	cp := astiav.AllocCodecParameters()
	cp.SetMediaType(mediaTypeToAstiav(mediaType))

	si := &packetorframetypes.StreamInfo{
		CodecParameters: cp,
	}

	pktInput := packet.BuildInput(pkt, si)
	return packetorframe.InputUnion{Packet: &pktInput}
}

// runSwitchTestCase sets up a fresh Switch, configures it per tc, calls
// GetState, and returns the result string.
func runSwitchTestCase(t *testing.T, tc switchTestCase) string {
	t.Helper()
	ctx := context.Background()

	sw := barrierstategetter.NewSwitch()

	// Set current value directly.
	sw.CurrentValue.Store(tc.currentValue)

	// Set keepUnless condition.
	sw.SetKeepUnless(buildKeepUnlessCond(tc.keepUnless))

	// Set next value directly (bypassing SetValue's commit logic).
	sw.NextValue.Store(tc.nextValue)

	// Build the SwitchOutput for the test's output ID.
	out := sw.Output(tc.outputID)

	// Build a mock packet.
	inputUnion := buildInputUnion(t, tc.mediaType, tc.isKeyFrame)

	// Query the barrier state.
	state, _ := out.GetState(ctx, inputUnion)

	return stateToString(state)
}

// testCases covers the same scenarios that the Lean DiffTest exercises.
var testCases = []switchTestCase{
	// ---- No pending switch (nextValue = MinInt32 => "none") ----

	{
		name:         "no_pending/output_matches_current",
		currentValue: 1, nextValue: math.MinInt32,
		outputID: 1, mediaType: "video", isKeyFrame: false,
		keepUnless: "keepunless",
		expected:   "pass",
	},
	{
		name:         "no_pending/output_does_not_match_current",
		currentValue: 1, nextValue: math.MinInt32,
		outputID: 2, mediaType: "video", isKeyFrame: false,
		keepUnless: "keepunless",
		expected:   "drop",
	},
	{
		name:         "no_pending/output_matches_current_audio",
		currentValue: 0, nextValue: math.MinInt32,
		outputID: 0, mediaType: "audio", isKeyFrame: false,
		keepUnless: "keepunless",
		expected:   "pass",
	},
	{
		name:         "no_pending/output_does_not_match_audio",
		currentValue: 0, nextValue: math.MinInt32,
		outputID: 1, mediaType: "audio", isKeyFrame: false,
		keepUnless: "keepunless",
		expected:   "drop",
	},

	// ---- Pending switch, keepUnless="always" (condition always matches) ----

	{
		name:         "pending_always/commit_output_matches_next",
		currentValue: 0, nextValue: 1,
		outputID: 1, mediaType: "video", isKeyFrame: false,
		keepUnless: "always",
		expected:   "pass",
	},
	{
		name:         "pending_always/commit_output_matches_old_current",
		currentValue: 0, nextValue: 1,
		outputID: 0, mediaType: "video", isKeyFrame: false,
		keepUnless: "always",
		expected:   "drop",
	},
	{
		name:         "pending_always/commit_output_matches_neither",
		currentValue: 0, nextValue: 1,
		outputID: 2, mediaType: "video", isKeyFrame: false,
		keepUnless: "always",
		expected:   "drop",
	},

	// ---- Pending switch, keepUnless="never" (condition never matches) ----

	{
		name:         "pending_never/no_commit_output_matches_current",
		currentValue: 0, nextValue: 1,
		outputID: 0, mediaType: "video", isKeyFrame: false,
		keepUnless: "never",
		expected:   "pass",
	},
	{
		name:         "pending_never/no_commit_output_matches_next",
		currentValue: 0, nextValue: 1,
		outputID: 1, mediaType: "video", isKeyFrame: false,
		keepUnless: "never",
		expected:   "drop",
	},
	{
		name:         "pending_never/no_commit_output_matches_neither",
		currentValue: 0, nextValue: 1,
		outputID: 2, mediaType: "video", isKeyFrame: false,
		keepUnless: "never",
		expected:   "drop",
	},

	// ---- Pending switch, keepUnless="keepunless" (video+keyframe) ----

	{
		name:         "pending_keepunless/video_keyframe_commit_output_is_next",
		currentValue: 0, nextValue: 1,
		outputID: 1, mediaType: "video", isKeyFrame: true,
		keepUnless: "keepunless",
		expected:   "pass",
	},
	{
		name:         "pending_keepunless/video_keyframe_commit_output_is_old",
		currentValue: 0, nextValue: 1,
		outputID: 0, mediaType: "video", isKeyFrame: true,
		keepUnless: "keepunless",
		expected:   "drop",
	},
	{
		name:         "pending_keepunless/video_nonkey_no_commit_output_is_current",
		currentValue: 0, nextValue: 1,
		outputID: 0, mediaType: "video", isKeyFrame: false,
		keepUnless: "keepunless",
		expected:   "pass",
	},
	{
		name:         "pending_keepunless/video_nonkey_no_commit_output_is_next",
		currentValue: 0, nextValue: 1,
		outputID: 1, mediaType: "video", isKeyFrame: false,
		keepUnless: "keepunless",
		expected:   "drop",
	},
	{
		name:         "pending_keepunless/audio_no_commit_output_is_current",
		currentValue: 0, nextValue: 1,
		outputID: 0, mediaType: "audio", isKeyFrame: false,
		keepUnless: "keepunless",
		expected:   "pass",
	},
	{
		name:         "pending_keepunless/audio_no_commit_output_is_next",
		currentValue: 0, nextValue: 1,
		outputID: 1, mediaType: "audio", isKeyFrame: false,
		keepUnless: "keepunless",
		expected:   "drop",
	},
	{
		name:         "pending_keepunless/audio_keyframe_no_commit_output_is_current",
		currentValue: 0, nextValue: 1,
		outputID: 0, mediaType: "audio", isKeyFrame: true,
		keepUnless: "keepunless",
		expected:   "pass",
	},

	// ---- Pending switch to same value (next == current) ----

	{
		name:         "pending_same_value/output_matches",
		currentValue: 2, nextValue: 2,
		outputID: 2, mediaType: "video", isKeyFrame: false,
		keepUnless: "always",
		expected:   "pass",
	},
	{
		name:         "pending_same_value/output_does_not_match",
		currentValue: 2, nextValue: 2,
		outputID: 3, mediaType: "video", isKeyFrame: false,
		keepUnless: "always",
		expected:   "drop",
	},

	// ---- Edge case: outputID=0, currentValue=0 ----

	{
		name:         "edge/outputID_zero_matches_default",
		currentValue: 0, nextValue: math.MinInt32,
		outputID: 0, mediaType: "video", isKeyFrame: false,
		keepUnless: "keepunless",
		expected:   "pass",
	},
	{
		name:         "edge/outputID_zero_does_not_match_nonzero_current",
		currentValue: 5, nextValue: math.MinInt32,
		outputID: 0, mediaType: "video", isKeyFrame: false,
		keepUnless: "keepunless",
		expected:   "drop",
	},
}

func TestSwitchBarrierDiffTest(t *testing.T) {
	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			got := runSwitchTestCase(t, tc)

			// Print in a format similar to the Lean DiffTest stdin/stdout protocol.
			nextStr := "none"
			if tc.nextValue != math.MinInt32 {
				nextStr = fmt.Sprintf("%d", tc.nextValue)
			}
			t.Logf("switch %d %s %d %s %t %s => %s (expected %s)",
				tc.currentValue, nextStr, tc.outputID,
				tc.mediaType, tc.isKeyFrame, tc.keepUnless,
				got, tc.expected,
			)

			if got != tc.expected {
				t.Errorf("MISMATCH: got %q, expected %q", got, tc.expected)
			}
		})
	}
}

// TestSwitchBarrierDiffTestProtocol runs the same test cases in the exact
// stdin/stdout protocol that the Lean DiffTest uses: one line per case on
// stdin, one result word per case on stdout.  This makes it easy to pipe
// the Go output into a diff against the Lean output.
func TestSwitchBarrierDiffTestProtocol(t *testing.T) {
	for _, tc := range testCases {
		got := runSwitchTestCase(t, tc)

		nextStr := "none"
		if tc.nextValue != math.MinInt32 {
			nextStr = fmt.Sprintf("%d", tc.nextValue)
		}
		// Print the input line (for reference) and the result.
		fmt.Printf("switch %d %s %d %s %t %s\n",
			tc.currentValue, nextStr, tc.outputID,
			tc.mediaType, tc.isKeyFrame, tc.keepUnless,
		)
		fmt.Println(got)

		if got != tc.expected {
			t.Errorf("case %q: got %q, expected %q", tc.name, got, tc.expected)
		}
	}
}
