// Tests auto-generated by AI agent.
package deblemish

import (
	"context"
	"image"
	"math"
	"sync/atomic"
	"testing"

	"github.com/asticode/go-astiav"
	testifyassert "github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/avpipeline/frame"
	"github.com/xaionaro-go/avpipeline/kernel"
	"github.com/xaionaro-go/avpipeline/packetorframe"
	packetorframetypes "github.com/xaionaro-go/avpipeline/packetorframe/types"
)

func makeVideoFrameInput(tb testing.TB) (packetorframe.InputUnion, func()) {
	tb.Helper()
	return makeVideoFrameInputWithSize(tb, 64, 64)
}

func makeVideoFrameInputWithSize(tb testing.TB, w, h int) (packetorframe.InputUnion, func()) {
	tb.Helper()
	cp := astiav.AllocCodecParameters()
	cp.SetMediaType(astiav.MediaTypeVideo)
	cp.SetWidth(w)
	cp.SetHeight(h)
	cp.SetPixelFormat(astiav.PixelFormatYuv420P)
	f := astiav.AllocFrame()
	f.SetWidth(w)
	f.SetHeight(h)
	f.SetPixelFormat(astiav.PixelFormatYuv420P)
	require.NoError(tb, f.AllocBuffer(32))
	streamInfo := &packetorframetypes.StreamInfo{
		CodecParameters: cp,
		StreamIndex:     0,
		StreamsCount:    1,
		TimeBase:        astiav.NewRational(1, 30),
	}
	frameInput := frame.BuildInput(f, 0, streamInfo)
	cleanup := func() {
		cp.Free()
		f.Free()
	}
	return packetorframe.InputUnion{Frame: &frameInput}, cleanup
}

func makeAudioFrameInput(tb testing.TB) (packetorframe.InputUnion, func()) {
	tb.Helper()
	cp := astiav.AllocCodecParameters()
	cp.SetMediaType(astiav.MediaTypeAudio)
	f := astiav.AllocFrame()
	streamInfo := &packetorframetypes.StreamInfo{
		CodecParameters: cp,
		StreamIndex:     0,
		StreamsCount:    1,
	}
	frameInput := frame.BuildInput(f, 0, streamInfo)
	cleanup := func() {
		cp.Free()
		f.Free()
	}
	return packetorframe.InputUnion{Frame: &frameInput}, cleanup
}

// makeCheckerboardYCbCr creates a YUV420 image with a checkerboard noise pattern
// in the Y plane. Bilateral filtering should measurably smooth this pattern.
func makeCheckerboardYCbCr(w, h int) *image.YCbCr {
	img := image.NewYCbCr(image.Rect(0, 0, w, h), image.YCbCrSubsampleRatio420)
	for y := range h {
		for x := range w {
			switch (x + y) % 2 {
			case 0:
				img.Y[y*img.YStride+x] = 200
			default:
				img.Y[y*img.YStride+x] = 40
			}
		}
	}
	// Fill chroma planes with neutral gray (128).
	for i := range img.Cb {
		img.Cb[i] = 128
		img.Cr[i] = 128
	}
	return img
}

// makeNoisyVideoFrameInput creates a frame with a checkerboard noise pattern
// so that bilateral filtering produces a measurable difference.
func makeNoisyVideoFrameInput(tb testing.TB, w, h int) (packetorframe.InputUnion, func()) {
	tb.Helper()
	input, cleanup := makeVideoFrameInputWithSize(tb, w, h)
	f := input.Frame.Frame

	img := makeCheckerboardYCbCr(w, h)
	require.NoError(tb, f.Data().FromImage(img))

	return input, cleanup
}

// frameToYCbCr extracts the Y/Cb/Cr planes from a frame as a Go image.
func frameToYCbCr(tb testing.TB, f *astiav.Frame) *image.YCbCr {
	tb.Helper()
	img := &image.YCbCr{}
	require.NoError(tb, f.Data().ToImage(img))
	return img
}

// computeYPlaneRMSE computes the root mean squared error between the Y planes
// of two YCbCr images. Returns math.MaxFloat64 if dimensions differ.
func computeYPlaneRMSE(a, b *image.YCbCr) float64 {
	if a.Rect.Dx() != b.Rect.Dx() || a.Rect.Dy() != b.Rect.Dy() {
		return math.MaxFloat64
	}
	w := a.Rect.Dx()
	h := a.Rect.Dy()

	var totalDiff int64
	for y := range h {
		for x := range w {
			va := int64(a.Y[y*a.YStride+x])
			vb := int64(b.Y[y*b.YStride+x])
			diff := va - vb
			totalDiff += diff * diff
		}
	}
	return math.Sqrt(float64(totalDiff) / float64(w*h))
}

// snapshotYPlane returns a copy of the Y plane data from a frame.
func snapshotYPlane(tb testing.TB, f *astiav.Frame) []byte {
	tb.Helper()
	img := frameToYCbCr(tb, f)
	cp := make([]byte, len(img.Y))
	copy(cp, img.Y)
	return cp
}

func TestNew_DefaultConfig(t *testing.T) {
	d, err := New(Config{})
	testifyassert.NoError(t, err)
	testifyassert.NotNil(t, d)
	defer func() { _ = d.Close(context.Background()) }()

	testifyassert.Equal(t, 10.0, d.SigmaS.Load())
	testifyassert.Equal(t, 0.1, d.SigmaR.Load())
	testifyassert.Equal(t, int64(-1), d.Diameter.Load())
	testifyassert.False(t, d.FaceOnly.Load())
}

func TestNew_FaceOnly_NoCVBuildTag(t *testing.T) {
	_, err := New(Config{FaceOnly: true})
	testifyassert.Error(t, err)
	testifyassert.Contains(t, err.Error(), "with_cv build tag")
}

func TestDeblemish_ImplementsAbstract(t *testing.T) {
	var _ kernel.Abstract = (*Deblemish)(nil)
}

func TestDeblemish_String(t *testing.T) {
	d, err := New(Config{})
	testifyassert.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()

	s := d.String()
	testifyassert.Contains(t, s, "Deblemish")
	testifyassert.Contains(t, s, "sigmaS=10")
	testifyassert.Contains(t, s, "sigmaR=0.1")
}

func TestDeblemish_GetObjectID(t *testing.T) {
	d, err := New(Config{})
	testifyassert.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()

	id := d.GetObjectID()
	testifyassert.NotEmpty(t, id)
}

func TestDeblemish_Close(t *testing.T) {
	d, err := New(Config{})
	testifyassert.NoError(t, err)
	testifyassert.NoError(t, d.Close(context.Background()))
}

func TestDeblemish_Generate(t *testing.T) {
	d, err := New(Config{})
	testifyassert.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()

	outputCh := make(chan packetorframe.OutputUnion, 10)
	testifyassert.NoError(t, d.Generate(context.Background(), outputCh))
	testifyassert.Len(t, outputCh, 0)
}

func TestDeblemish_SendInput_NilFrame_Passthrough(t *testing.T) {
	d, err := New(Config{})
	testifyassert.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()

	outputCh := make(chan packetorframe.OutputUnion, 10)
	err = d.SendInput(context.Background(), packetorframe.InputUnion{}, outputCh)
	testifyassert.NoError(t, err)
	testifyassert.Len(t, outputCh, 1)
}

func TestDeblemish_SendInput_Disabled_Passthrough(t *testing.T) {
	d, err := New(Config{})
	testifyassert.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()

	enabled := &atomic.Bool{}
	enabled.Store(false)
	d.Enabled = enabled

	input, cleanup := makeVideoFrameInput(t)
	defer cleanup()

	outputCh := make(chan packetorframe.OutputUnion, 10)
	err = d.SendInput(context.Background(), input, outputCh)
	testifyassert.NoError(t, err)
	testifyassert.Len(t, outputCh, 1)
}

func TestDeblemish_SendInput_AudioFrame_Passthrough(t *testing.T) {
	d, err := New(Config{})
	testifyassert.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()

	input, cleanup := makeAudioFrameInput(t)
	defer cleanup()

	outputCh := make(chan packetorframe.OutputUnion, 10)
	err = d.SendInput(context.Background(), input, outputCh)
	testifyassert.NoError(t, err)
	testifyassert.Len(t, outputCh, 1)
}

func TestDeblemish_ResolvedBackend(t *testing.T) {
	d, err := New(Config{Backend: BackendCPU})
	testifyassert.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()
	testifyassert.Equal(t, BackendCPU, d.ResolvedBackend())
}

func TestDeblemish_RuntimeParamChange(t *testing.T) {
	d, err := New(Config{})
	testifyassert.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()

	d.SigmaS.Store(20.0)
	testifyassert.Equal(t, 20.0, d.SigmaS.Load())

	d.SigmaR.Store(0.5)
	testifyassert.Equal(t, 0.5, d.SigmaR.Load())

	d.Diameter.Store(7)
	testifyassert.Equal(t, int64(7), d.Diameter.Load())
}

func TestBackend_String(t *testing.T) {
	testifyassert.Equal(t, "Auto", BackendAuto.String())
	testifyassert.Equal(t, "CPU", BackendCPU.String())
	testifyassert.Equal(t, "CUDA", BackendCUDA.String())
	testifyassert.Equal(t, "OpenCL", BackendOpenCL.String())
	testifyassert.Equal(t, "Vulkan", BackendVulkan.String())
	testifyassert.Equal(t, "Unknown", Backend(99).String())
}

func TestConfig_SetDefaults(t *testing.T) {
	cfg := Config{}
	cfg.setDefaults()
	testifyassert.Equal(t, 10.0, cfg.SigmaS)
	testifyassert.Equal(t, 0.1, cfg.SigmaR)
	testifyassert.Equal(t, -1, cfg.Diameter)
	testifyassert.Equal(t, 1.1, cfg.FaceScaleFactor)
	testifyassert.Equal(t, 3, cfg.FaceMinNeighbors)
	testifyassert.Equal(t, 30, cfg.FaceMinSize.X)
	testifyassert.Equal(t, 30, cfg.FaceMinSize.Y)
}

func TestConfig_SetDefaults_PreservesExplicit(t *testing.T) {
	cfg := Config{
		SigmaS:   50,
		SigmaR:   0.5,
		Diameter: 7,
	}
	cfg.setDefaults()
	testifyassert.Equal(t, 50.0, cfg.SigmaS)
	testifyassert.Equal(t, 0.5, cfg.SigmaR)
	testifyassert.Equal(t, 7, cfg.Diameter)
}

func TestDeblemish_SendInput_WholeFrame_CPU(t *testing.T) {
	d, err := New(Config{Backend: BackendCPU})
	require.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()

	input, cleanup := makeVideoFrameInputWithSize(t, 320, 240)
	defer cleanup()

	outputCh := make(chan packetorframe.OutputUnion, 10)
	err = d.SendInput(context.Background(), input, outputCh)
	require.NoError(t, err)
	testifyassert.Len(t, outputCh, 1)

	output := <-outputCh
	testifyassert.NotNil(t, output.Frame)
}

func TestDeblemish_SendInput_WholeFrame_RebuildOnFormatChange(t *testing.T) {
	d, err := New(Config{Backend: BackendCPU})
	require.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()

	// First frame: 320x240.
	input1, cleanup1 := makeVideoFrameInputWithSize(t, 320, 240)
	defer cleanup1()
	outputCh := make(chan packetorframe.OutputUnion, 10)
	require.NoError(t, d.SendInput(context.Background(), input1, outputCh))
	testifyassert.Len(t, outputCh, 1)
	<-outputCh

	// Second frame: different size triggers graph rebuild.
	input2, cleanup2 := makeVideoFrameInputWithSize(t, 160, 120)
	defer cleanup2()
	require.NoError(t, d.SendInput(context.Background(), input2, outputCh))
	testifyassert.Len(t, outputCh, 1)
}

func TestDeblemish_SendInput_WholeFrame_RuntimeParamSync(t *testing.T) {
	d, err := New(Config{Backend: BackendCPU})
	require.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()

	input, cleanup := makeVideoFrameInputWithSize(t, 320, 240)
	defer cleanup()

	// Process first frame to initialize graph.
	outputCh := make(chan packetorframe.OutputUnion, 10)
	require.NoError(t, d.SendInput(context.Background(), input, outputCh))
	<-outputCh

	// Change parameters at runtime.
	d.SigmaS.Store(20.0)
	d.SigmaR.Store(0.5)

	// Process second frame with new params (should use SendCommand, not rebuild).
	input2, cleanup2 := makeVideoFrameInputWithSize(t, 320, 240)
	defer cleanup2()
	require.NoError(t, d.SendInput(context.Background(), input2, outputCh))
	testifyassert.Len(t, outputCh, 1)

	// Verify params were synced.
	testifyassert.Equal(t, 20.0, d.lastSigmaS)
	testifyassert.Equal(t, 0.5, d.lastSigmaR)
}

func TestDeblemish_SendInput_FaceOnly_NoCVReturnsError(t *testing.T) {
	d, err := New(Config{Backend: BackendCPU})
	require.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()

	// Enable face-only at runtime.
	d.FaceOnly.Store(true)

	input, cleanup := makeVideoFrameInputWithSize(t, 320, 240)
	defer cleanup()

	outputCh := make(chan packetorframe.OutputUnion, 10)
	err = d.SendInput(context.Background(), input, outputCh)
	testifyassert.Error(t, err)
	testifyassert.Contains(t, err.Error(), "with_cv build tag")
}

func TestDeblemish_SendInput_Enabled_NilMeansAlwaysOn(t *testing.T) {
	d, err := New(Config{Backend: BackendCPU})
	require.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()

	// Enabled is nil by default, which means always on.
	testifyassert.Nil(t, d.Enabled)

	input, cleanup := makeVideoFrameInputWithSize(t, 320, 240)
	defer cleanup()

	outputCh := make(chan packetorframe.OutputUnion, 10)
	err = d.SendInput(context.Background(), input, outputCh)
	require.NoError(t, err)
	testifyassert.Len(t, outputCh, 1)
}

func TestDeblemish_Close_Idempotent(t *testing.T) {
	d, err := New(Config{})
	require.NoError(t, err)

	testifyassert.NoError(t, d.Close(context.Background()))
	testifyassert.NoError(t, d.Close(context.Background()))
}

func TestResolveBackend_Explicit(t *testing.T) {
	testifyassert.Equal(t, BackendCPU, resolveBackend(BackendCPU))
	testifyassert.Equal(t, BackendCUDA, resolveBackend(BackendCUDA))
	testifyassert.Equal(t, BackendOpenCL, resolveBackend(BackendOpenCL))
	testifyassert.Equal(t, BackendVulkan, resolveBackend(BackendVulkan))
}

func TestResolveBackend_Auto(t *testing.T) {
	b := resolveBackend(BackendAuto)
	// Auto should resolve to some concrete backend.
	testifyassert.NotEqual(t, BackendAuto, b)
}

// TestDeblemish_SendInput_WholeFrame_PixelsModified verifies that bilateral
// filtering actually changes pixel values when given a noisy input frame.
func TestDeblemish_SendInput_WholeFrame_PixelsModified(t *testing.T) {
	d, err := New(Config{Backend: BackendCPU})
	require.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()

	input, cleanup := makeNoisyVideoFrameInput(t, 320, 240)
	defer cleanup()

	inputSnapshot := snapshotYPlane(t, input.Frame.Frame)

	outputCh := make(chan packetorframe.OutputUnion, 10)
	require.NoError(t, d.SendInput(context.Background(), input, outputCh))
	require.Len(t, outputCh, 1)

	output := <-outputCh
	require.NotNil(t, output.Frame)

	// Verify that output pixels differ from input: bilateral filter smoothed the noise.
	inputImg := makeCheckerboardYCbCr(320, 240)
	outputImg := frameToYCbCr(t, output.Frame.Frame)
	rmse := computeYPlaneRMSE(inputImg, outputImg)
	testifyassert.Greater(t, rmse, 0.1,
		"bilateral filter should measurably change a noisy frame (RMSE=%f)", rmse)

	// Verify the output isn't all zeros (filter produced actual content).
	hasNonZero := false
	for _, b := range outputImg.Y {
		if b != 0 {
			hasNonZero = true
			break
		}
	}
	testifyassert.True(t, hasNonZero, "output frame should contain non-zero pixel data")

	// Verify input frame itself was not mutated by the filter (filter works on a copy).
	currentInput := snapshotYPlane(t, input.Frame.Frame)
	testifyassert.Equal(t, inputSnapshot, currentInput,
		"input frame should not be mutated by the filter")
}

// TestDeblemish_SendInput_Passthrough_PixelsUnchanged verifies that when
// deblemish is disabled, the output frame is byte-identical to the input.
func TestDeblemish_SendInput_Passthrough_PixelsUnchanged(t *testing.T) {
	d, err := New(Config{Backend: BackendCPU})
	require.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()

	enabled := &atomic.Bool{}
	enabled.Store(false)
	d.Enabled = enabled

	input, cleanup := makeNoisyVideoFrameInput(t, 320, 240)
	defer cleanup()

	inputSnapshot := snapshotYPlane(t, input.Frame.Frame)

	outputCh := make(chan packetorframe.OutputUnion, 10)
	require.NoError(t, d.SendInput(context.Background(), input, outputCh))
	require.Len(t, outputCh, 1)

	output := <-outputCh
	require.NotNil(t, output.Frame)

	// In passthrough mode, output references the same data (CloneAsReferenced).
	outputSnapshot := snapshotYPlane(t, output.Frame.Frame)
	testifyassert.Equal(t, inputSnapshot, outputSnapshot,
		"passthrough mode should produce byte-identical pixel data")
}

// TestDeblemish_SendInput_DynamicToggle verifies that passthrough can be
// toggled at runtime between frames.
func TestDeblemish_SendInput_DynamicToggle(t *testing.T) {
	d, err := New(Config{Backend: BackendCPU})
	require.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()

	enabled := &atomic.Bool{}
	enabled.Store(true)
	d.Enabled = enabled

	outputCh := make(chan packetorframe.OutputUnion, 10)

	// Frame 1: filter enabled — should modify pixels.
	input1, cleanup1 := makeNoisyVideoFrameInput(t, 320, 240)
	defer cleanup1()
	input1Snapshot := snapshotYPlane(t, input1.Frame.Frame)

	require.NoError(t, d.SendInput(context.Background(), input1, outputCh))
	require.Len(t, outputCh, 1)
	out1 := <-outputCh
	require.NotNil(t, out1.Frame)

	out1Snapshot := snapshotYPlane(t, out1.Frame.Frame)
	testifyassert.NotEqual(t, input1Snapshot, out1Snapshot,
		"with filter enabled, output should differ from input")

	// Frame 2: toggle to disabled (passthrough) — should NOT modify pixels.
	enabled.Store(false)

	input2, cleanup2 := makeNoisyVideoFrameInput(t, 320, 240)
	defer cleanup2()
	input2Snapshot := snapshotYPlane(t, input2.Frame.Frame)

	require.NoError(t, d.SendInput(context.Background(), input2, outputCh))
	require.Len(t, outputCh, 1)
	out2 := <-outputCh
	require.NotNil(t, out2.Frame)

	out2Snapshot := snapshotYPlane(t, out2.Frame.Frame)
	testifyassert.Equal(t, input2Snapshot, out2Snapshot,
		"with filter disabled, output should be identical to input")

	// Frame 3: toggle back to enabled — should modify pixels again.
	enabled.Store(true)

	input3, cleanup3 := makeNoisyVideoFrameInput(t, 320, 240)
	defer cleanup3()
	input3Snapshot := snapshotYPlane(t, input3.Frame.Frame)

	require.NoError(t, d.SendInput(context.Background(), input3, outputCh))
	require.Len(t, outputCh, 1)
	out3 := <-outputCh
	require.NotNil(t, out3.Frame)

	out3Snapshot := snapshotYPlane(t, out3.Frame.Frame)
	testifyassert.NotEqual(t, input3Snapshot, out3Snapshot,
		"with filter re-enabled, output should differ from input again")
}

// TestDeblemish_SendInput_HighSigma_StrongerSmoothing verifies that increasing
// sigmaS produces stronger smoothing (higher RMSE from original).
func TestDeblemish_SendInput_HighSigma_StrongerSmoothing(t *testing.T) {
	referenceImg := makeCheckerboardYCbCr(160, 120)

	// Low sigma run.
	dLow, err := New(Config{Backend: BackendCPU, SigmaS: 5, SigmaR: 0.1})
	require.NoError(t, err)
	defer func() { _ = dLow.Close(context.Background()) }()

	inputLow, cleanupLow := makeNoisyVideoFrameInput(t, 160, 120)
	defer cleanupLow()

	outputCh := make(chan packetorframe.OutputUnion, 10)
	require.NoError(t, dLow.SendInput(context.Background(), inputLow, outputCh))
	require.Len(t, outputCh, 1)
	outLow := <-outputCh

	outLowImg := frameToYCbCr(t, outLow.Frame.Frame)
	rmseLow := computeYPlaneRMSE(referenceImg, outLowImg)

	// High sigma run.
	dHigh, err := New(Config{Backend: BackendCPU, SigmaS: 50, SigmaR: 0.5})
	require.NoError(t, err)
	defer func() { _ = dHigh.Close(context.Background()) }()

	inputHigh, cleanupHigh := makeNoisyVideoFrameInput(t, 160, 120)
	defer cleanupHigh()

	outputCh2 := make(chan packetorframe.OutputUnion, 10)
	require.NoError(t, dHigh.SendInput(context.Background(), inputHigh, outputCh2))
	require.Len(t, outputCh2, 1)
	outHigh := <-outputCh2

	outHighImg := frameToYCbCr(t, outHigh.Frame.Frame)
	rmseHigh := computeYPlaneRMSE(referenceImg, outHighImg)

	// Higher sigma should produce stronger smoothing, i.e. higher deviation from original.
	testifyassert.Greater(t, rmseHigh, rmseLow,
		"higher sigma should produce stronger smoothing (rmseLow=%f, rmseHigh=%f)",
		rmseLow, rmseHigh)

	// Both should be non-trivial (any smoothing produces measurable RMSE > 0).
	testifyassert.Greater(t, rmseLow, 0.01, "even low sigma should produce measurable change")
	testifyassert.Greater(t, rmseHigh, 0.01, "high sigma should produce significant change")
}

// TestDeblemish_SendInput_MultipleFrames_Consistent verifies that processing
// multiple identical frames produces consistent output.
func TestDeblemish_SendInput_MultipleFrames_Consistent(t *testing.T) {
	d, err := New(Config{Backend: BackendCPU})
	require.NoError(t, err)
	defer func() { _ = d.Close(context.Background()) }()

	outputCh := make(chan packetorframe.OutputUnion, 10)
	var outputSnapshots [][]byte

	for i := range 3 {
		input, cleanup := makeNoisyVideoFrameInput(t, 160, 120)

		require.NoError(t, d.SendInput(context.Background(), input, outputCh),
			"frame %d", i)
		require.Len(t, outputCh, 1, "frame %d", i)

		out := <-outputCh
		require.NotNil(t, out.Frame, "frame %d", i)

		snap := snapshotYPlane(t, out.Frame.Frame)
		outputSnapshots = append(outputSnapshots, snap)

		cleanup()
	}

	// All outputs should be identical since inputs are identical.
	testifyassert.Equal(t, outputSnapshots[0], outputSnapshots[1],
		"consistent input should produce consistent output (frame 0 vs 1)")
	testifyassert.Equal(t, outputSnapshots[1], outputSnapshots[2],
		"consistent input should produce consistent output (frame 1 vs 2)")
}

func BenchmarkDeblemish_WholeFrame_CPU(b *testing.B) {
	d, err := New(Config{Backend: BackendCPU})
	if err != nil {
		b.Fatal(err)
	}
	defer func() { _ = d.Close(context.Background()) }()

	// Initialize filter graph with first frame.
	initInput, initCleanup := makeNoisyVideoFrameInput(b, 640, 480)
	outputCh := make(chan packetorframe.OutputUnion, 10)
	if err := d.SendInput(context.Background(), initInput, outputCh); err != nil {
		b.Fatal(err)
	}
	<-outputCh
	initCleanup()

	b.ResetTimer()
	for range b.N {
		input, cleanup := makeNoisyVideoFrameInput(b, 640, 480)
		if err := d.SendInput(context.Background(), input, outputCh); err != nil {
			b.Fatal(err)
		}
		<-outputCh
		cleanup()
	}
}

func BenchmarkDeblemish_Passthrough(b *testing.B) {
	d, err := New(Config{Backend: BackendCPU})
	if err != nil {
		b.Fatal(err)
	}
	defer func() { _ = d.Close(context.Background()) }()

	enabled := &atomic.Bool{}
	enabled.Store(false)
	d.Enabled = enabled

	b.ResetTimer()
	outputCh := make(chan packetorframe.OutputUnion, 10)
	for range b.N {
		input, cleanup := makeNoisyVideoFrameInput(b, 640, 480)
		if err := d.SendInput(context.Background(), input, outputCh); err != nil {
			b.Fatal(err)
		}
		<-outputCh
		cleanup()
	}
}

