// Tests auto-generated by AI agent.
package deblemish

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestFilterStringForBackend_CPU(t *testing.T) {
	s := filterStringForBackend(BackendCPU, 10, 0.1, -1)
	assert.Equal(t, "bilateral=sigmaS=10:sigmaR=0.1", s)
}

func TestFilterStringForBackend_CPU_CustomParams(t *testing.T) {
	s := filterStringForBackend(BackendCPU, 50, 0.5, 7)
	assert.Equal(t, "bilateral=sigmaS=50:sigmaR=0.5", s)
}

func TestFilterStringForBackend_CUDA(t *testing.T) {
	s := filterStringForBackend(BackendCUDA, 10, 0.1, -1)
	assert.Contains(t, s, "hwupload_cuda")
	assert.Contains(t, s, "bilateral_cuda=sigmaS=10:sigmaR=0.1:window_size=21")
	assert.Contains(t, s, "hwdownload")
}

func TestFilterStringForBackend_CUDA_ExplicitWindowSize(t *testing.T) {
	s := filterStringForBackend(BackendCUDA, 10, 0.1, 5)
	assert.Contains(t, s, "window_size=5")
}

func TestFilterStringForBackend_OpenCL(t *testing.T) {
	s := filterStringForBackend(BackendOpenCL, 10, 0.1, -1)
	assert.Contains(t, s, "hwupload")
	assert.Contains(t, s, "nlmeans_opencl")
	assert.Contains(t, s, "hwdownload")
}

func TestFilterStringForBackend_Vulkan(t *testing.T) {
	s := filterStringForBackend(BackendVulkan, 10, 0.1, -1)
	assert.Contains(t, s, "hwupload")
	assert.Contains(t, s, "libplacebo")
	assert.Contains(t, s, "hwdownload")
}
