// Tests auto-generated by AI agent.
package avfilter

import (
	"context"
	"testing"

	"github.com/asticode/go-astiav"
	testifyassert "github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestSimpleGraph_ImplementsFrameFilter(t *testing.T) {
	var _ FrameFilter = (*SimpleGraph)(nil)
}

func TestSimpleVideoGraph_Null(t *testing.T) {
	ctx := context.Background()
	g, err := NewSimpleVideoGraph(ctx, "null", SimpleVideoGraphConfig{
		Width:       320,
		Height:      240,
		PixelFormat: astiav.PixelFormatYuv420P,
		TimeBase:    astiav.NewRational(1, 30),
	})
	require.NoError(t, err)
	defer g.Close()

	f := astiav.AllocFrame()
	defer f.Free()
	f.SetWidth(320)
	f.SetHeight(240)
	f.SetPixelFormat(astiav.PixelFormatYuv420P)
	require.NoError(t, f.AllocBuffer(32))

	frames, err := g.ProcessFrame(ctx, f)
	require.NoError(t, err)
	require.Len(t, frames, 1)
	testifyassert.Equal(t, 320, frames[0].Width())
	testifyassert.Equal(t, 240, frames[0].Height())
}

func TestSimpleVideoGraph_Scale(t *testing.T) {
	ctx := context.Background()
	g, err := NewSimpleVideoGraph(ctx, "scale=160:120", SimpleVideoGraphConfig{
		Width:       320,
		Height:      240,
		PixelFormat: astiav.PixelFormatYuv420P,
		TimeBase:    astiav.NewRational(1, 30),
	})
	require.NoError(t, err)
	defer g.Close()

	f := astiav.AllocFrame()
	defer f.Free()
	f.SetWidth(320)
	f.SetHeight(240)
	f.SetPixelFormat(astiav.PixelFormatYuv420P)
	require.NoError(t, f.AllocBuffer(32))

	frames, err := g.ProcessFrame(ctx, f)
	require.NoError(t, err)
	require.Len(t, frames, 1)
	testifyassert.Equal(t, 160, frames[0].Width())
	testifyassert.Equal(t, 120, frames[0].Height())
}

func TestSimpleVideoGraph_Crop(t *testing.T) {
	ctx := context.Background()
	g, err := NewSimpleVideoGraph(ctx, CropFilter(100, 100, 10, 10), SimpleVideoGraphConfig{
		Width:       320,
		Height:      240,
		PixelFormat: astiav.PixelFormatYuv420P,
		TimeBase:    astiav.NewRational(1, 30),
	})
	require.NoError(t, err)
	defer g.Close()

	f := astiav.AllocFrame()
	defer f.Free()
	f.SetWidth(320)
	f.SetHeight(240)
	f.SetPixelFormat(astiav.PixelFormatYuv420P)
	require.NoError(t, f.AllocBuffer(32))

	frames, err := g.ProcessFrame(ctx, f)
	require.NoError(t, err)
	require.Len(t, frames, 1)
	testifyassert.Equal(t, 100, frames[0].Width())
	testifyassert.Equal(t, 100, frames[0].Height())
}

func TestSimpleVideoGraph_Transpose(t *testing.T) {
	ctx := context.Background()
	g, err := NewSimpleVideoGraph(ctx, "transpose=1", SimpleVideoGraphConfig{
		Width:       320,
		Height:      240,
		PixelFormat: astiav.PixelFormatYuv420P,
		TimeBase:    astiav.NewRational(1, 30),
	})
	require.NoError(t, err)
	defer g.Close()

	f := astiav.AllocFrame()
	defer f.Free()
	f.SetWidth(320)
	f.SetHeight(240)
	f.SetPixelFormat(astiav.PixelFormatYuv420P)
	require.NoError(t, f.AllocBuffer(32))

	frames, err := g.ProcessFrame(ctx, f)
	require.NoError(t, err)
	require.Len(t, frames, 1)
	testifyassert.Equal(t, 240, frames[0].Width())
	testifyassert.Equal(t, 320, frames[0].Height())
}

func TestSimpleVideoGraph_Chain(t *testing.T) {
	ctx := context.Background()
	g, err := NewSimpleVideoGraph(ctx, "scale=640:480,transpose=1", SimpleVideoGraphConfig{
		Width:       320,
		Height:      240,
		PixelFormat: astiav.PixelFormatYuv420P,
		TimeBase:    astiav.NewRational(1, 30),
	})
	require.NoError(t, err)
	defer g.Close()

	f := astiav.AllocFrame()
	defer f.Free()
	f.SetWidth(320)
	f.SetHeight(240)
	f.SetPixelFormat(astiav.PixelFormatYuv420P)
	require.NoError(t, f.AllocBuffer(32))

	frames, err := g.ProcessFrame(ctx, f)
	require.NoError(t, err)
	require.Len(t, frames, 1)
	testifyassert.Equal(t, 480, frames[0].Width())
	testifyassert.Equal(t, 640, frames[0].Height())
}

func TestSimpleAudioGraph_ANull(t *testing.T) {
	ctx := context.Background()

	g, err := NewSimpleAudioGraph(ctx, "anull", SimpleAudioGraphConfig{
		SampleRate:    44100,
		SampleFormat:  astiav.SampleFormatFltp,
		ChannelLayout: astiav.ChannelLayoutMono,
		TimeBase:      astiav.NewRational(1, 44100),
	})
	require.NoError(t, err)
	defer g.Close()

	f := astiav.AllocFrame()
	defer f.Free()
	f.SetSampleRate(44100)
	f.SetSampleFormat(astiav.SampleFormatFltp)
	f.SetChannelLayout(astiav.ChannelLayoutMono)
	f.SetNbSamples(1024)
	require.NoError(t, f.AllocBuffer(0))

	frames, err := g.ProcessFrame(ctx, f)
	require.NoError(t, err)
	require.Len(t, frames, 1)
	testifyassert.Equal(t, 1024, frames[0].NbSamples())
}

func TestSimpleVideoGraphFromFrame(t *testing.T) {
	ctx := context.Background()

	f := astiav.AllocFrame()
	defer f.Free()
	f.SetWidth(320)
	f.SetHeight(240)
	f.SetPixelFormat(astiav.PixelFormatYuv420P)
	require.NoError(t, f.AllocBuffer(32))

	g, err := NewSimpleVideoGraphFromFrame(ctx, "null", f, astiav.NewRational(1, 30))
	require.NoError(t, err)
	defer g.Close()

	frames, err := g.ProcessFrame(ctx, f)
	require.NoError(t, err)
	require.Len(t, frames, 1)
	testifyassert.Equal(t, 320, frames[0].Width())
	testifyassert.Equal(t, 240, frames[0].Height())
}

func TestSimpleVideoGraph_MultipleFrames(t *testing.T) {
	ctx := context.Background()
	g, err := NewSimpleVideoGraph(ctx, "null", SimpleVideoGraphConfig{
		Width:       320,
		Height:      240,
		PixelFormat: astiav.PixelFormatYuv420P,
		TimeBase:    astiav.NewRational(1, 30),
	})
	require.NoError(t, err)
	defer g.Close()

	for i := 0; i < 10; i++ {
		f := astiav.AllocFrame()
		f.SetWidth(320)
		f.SetHeight(240)
		f.SetPixelFormat(astiav.PixelFormatYuv420P)
		f.SetPts(int64(i))
		require.NoError(t, f.AllocBuffer(32))

		frames, err := g.ProcessFrame(ctx, f)
		require.NoError(t, err)
		require.Len(t, frames, 1)
		testifyassert.Equal(t, int64(i), frames[0].Pts())
		f.Free()
	}
}

func TestSimpleVideoGraph_InvalidFilter(t *testing.T) {
	ctx := context.Background()
	_, err := NewSimpleVideoGraph(ctx, "nonexistent_filter_xyz", SimpleVideoGraphConfig{
		Width:       320,
		Height:      240,
		PixelFormat: astiav.PixelFormatYuv420P,
		TimeBase:    astiav.NewRational(1, 30),
	})
	testifyassert.Error(t, err)
}

func TestSimpleGraph_GetOutputStreams(t *testing.T) {
	ctx := context.Background()
	g, err := NewSimpleVideoGraph(ctx, "null", SimpleVideoGraphConfig{
		Width:       320,
		Height:      240,
		PixelFormat: astiav.PixelFormatYuv420P,
		TimeBase:    astiav.NewRational(1, 30),
	})
	require.NoError(t, err)
	defer g.Close()

	testifyassert.Equal(t, []int{0}, g.GetOutputStreams())
}

func TestSimpleGraph_CloseIdempotent(t *testing.T) {
	ctx := context.Background()
	g, err := NewSimpleVideoGraph(ctx, "null", SimpleVideoGraphConfig{
		Width:       320,
		Height:      240,
		PixelFormat: astiav.PixelFormatYuv420P,
		TimeBase:    astiav.NewRational(1, 30),
	})
	require.NoError(t, err)
	testifyassert.NoError(t, g.Close())
	testifyassert.NoError(t, g.Close())
}

func TestSimpleGraph_AddFrameGetFrame(t *testing.T) {
	ctx := context.Background()
	g, err := NewSimpleVideoGraph(ctx, "null", SimpleVideoGraphConfig{
		Width:       320,
		Height:      240,
		PixelFormat: astiav.PixelFormatYuv420P,
		TimeBase:    astiav.NewRational(1, 30),
	})
	require.NoError(t, err)
	defer g.Close()

	f := astiav.AllocFrame()
	defer f.Free()
	f.SetWidth(320)
	f.SetHeight(240)
	f.SetPixelFormat(astiav.PixelFormatYuv420P)
	require.NoError(t, f.AllocBuffer(32))

	err = g.AddFrame(0, f, astiav.NewBuffersrcFlags(astiav.BuffersrcFlagKeepRef))
	require.NoError(t, err)

	out := astiav.AllocFrame()
	defer out.Free()
	err = g.GetFrame(0, out, astiav.NewBuffersinkFlags())
	require.NoError(t, err)
	testifyassert.Equal(t, 320, out.Width())
	testifyassert.Equal(t, 240, out.Height())
}

func TestSimpleGraph_GetFrame_Eagain(t *testing.T) {
	ctx := context.Background()
	g, err := NewSimpleVideoGraph(ctx, "null", SimpleVideoGraphConfig{
		Width:       320,
		Height:      240,
		PixelFormat: astiav.PixelFormatYuv420P,
		TimeBase:    astiav.NewRational(1, 30),
	})
	require.NoError(t, err)
	defer g.Close()

	out := astiav.AllocFrame()
	defer out.Free()
	err = g.GetFrame(0, out, astiav.NewBuffersinkFlags())
	testifyassert.ErrorIs(t, err, astiav.ErrEagain)
}

func TestSimpleVideoGraph_BoxBlur(t *testing.T) {
	ctx := context.Background()
	g, err := NewSimpleVideoGraph(ctx, BoxBlurFilter(2, 1), SimpleVideoGraphConfig{
		Width:       320,
		Height:      240,
		PixelFormat: astiav.PixelFormatYuv420P,
		TimeBase:    astiav.NewRational(1, 30),
	})
	require.NoError(t, err)
	defer g.Close()

	f := astiav.AllocFrame()
	defer f.Free()
	f.SetWidth(320)
	f.SetHeight(240)
	f.SetPixelFormat(astiav.PixelFormatYuv420P)
	require.NoError(t, f.AllocBuffer(32))

	frames, err := g.ProcessFrame(ctx, f)
	require.NoError(t, err)
	require.Len(t, frames, 1)
	testifyassert.Equal(t, 320, frames[0].Width())
	testifyassert.Equal(t, 240, frames[0].Height())
}
