// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: avpipeline.proto

package avpipeline

import (
	libav "github.com/xaionaro-go/avpipeline/protobuf/libav"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MonitorEventType int32

const (
	MonitorEventType_UNDEFINED_EVENT_TYPE          MonitorEventType = 0
	MonitorEventType_EVENT_TYPE_RECEIVE            MonitorEventType = 1
	MonitorEventType_EVENT_TYPE_SEND               MonitorEventType = 2
	MonitorEventType_EVENT_TYPE_KERNEL_OUTPUT_SEND MonitorEventType = 128
)

// Enum value maps for MonitorEventType.
var (
	MonitorEventType_name = map[int32]string{
		0:   "UNDEFINED_EVENT_TYPE",
		1:   "EVENT_TYPE_RECEIVE",
		2:   "EVENT_TYPE_SEND",
		128: "EVENT_TYPE_KERNEL_OUTPUT_SEND",
	}
	MonitorEventType_value = map[string]int32{
		"UNDEFINED_EVENT_TYPE":          0,
		"EVENT_TYPE_RECEIVE":            1,
		"EVENT_TYPE_SEND":               2,
		"EVENT_TYPE_KERNEL_OUTPUT_SEND": 128,
	}
)

func (x MonitorEventType) Enum() *MonitorEventType {
	p := new(MonitorEventType)
	*p = x
	return p
}

func (x MonitorEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MonitorEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_avpipeline_proto_enumTypes[0].Descriptor()
}

func (MonitorEventType) Type() protoreflect.EnumType {
	return &file_avpipeline_proto_enumTypes[0]
}

func (x MonitorEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MonitorEventType.Descriptor instead.
func (MonitorEventType) EnumDescriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{0}
}

type Node struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsServing           bool                   `protobuf:"varint,4,opt,name=is_serving,json=isServing,proto3" json:"is_serving,omitempty"`
	Counters            *NodeCounters          `protobuf:"bytes,5,opt,name=counters,proto3" json:"counters,omitempty"`
	TodoPublishingNodes []*Node                `protobuf:"bytes,6,rep,name=todo_publishing_nodes,json=todoPublishingNodes,proto3" json:"todo_publishing_nodes,omitempty"` // is not currently reported
	ConsumingNodes      []*Node                `protobuf:"bytes,7,rep,name=consuming_nodes,json=consumingNodes,proto3" json:"consuming_nodes,omitempty"`
	// first_frame_unix_ns is the unix-nanosecond timestamp at which
	// this node's processor emitted its first output packet/frame.
	// 0 (default) means "no output observed yet". Used by
	// ffstreamctl stats first-frame to walk the pipeline graph and
	// identify the exact node where flow stalled (#350 debugging-gaps
	// Item 1: per-layer first-frame timing pinpoints cascade-EOF
	// wedges).
	FirstFrameUnixNs int64 `protobuf:"varint,8,opt,name=first_frame_unix_ns,json=firstFrameUnixNs,proto3" json:"first_frame_unix_ns,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_avpipeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Node) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Node) GetIsServing() bool {
	if x != nil {
		return x.IsServing
	}
	return false
}

func (x *Node) GetCounters() *NodeCounters {
	if x != nil {
		return x.Counters
	}
	return nil
}

func (x *Node) GetTodoPublishingNodes() []*Node {
	if x != nil {
		return x.TodoPublishingNodes
	}
	return nil
}

func (x *Node) GetConsumingNodes() []*Node {
	if x != nil {
		return x.ConsumingNodes
	}
	return nil
}

func (x *Node) GetFirstFrameUnixNs() int64 {
	if x != nil {
		return x.FirstFrameUnixNs
	}
	return 0
}

type NodeCounters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      *NodeCountersSection   `protobuf:"bytes,1,opt,name=received,proto3" json:"received,omitempty"`
	Processed     *NodeCountersSection   `protobuf:"bytes,2,opt,name=processed,proto3" json:"processed,omitempty"`
	Missed        *NodeCountersSection   `protobuf:"bytes,3,opt,name=missed,proto3" json:"missed,omitempty"`
	Generated     *NodeCountersSection   `protobuf:"bytes,4,opt,name=generated,proto3" json:"generated,omitempty"`
	Omitted       *NodeCountersSection   `protobuf:"bytes,5,opt,name=omitted,proto3" json:"omitted,omitempty"`
	Sent          *NodeCountersSection   `protobuf:"bytes,6,opt,name=sent,proto3" json:"sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCounters) Reset() {
	*x = NodeCounters{}
	mi := &file_avpipeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCounters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCounters) ProtoMessage() {}

func (x *NodeCounters) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCounters.ProtoReflect.Descriptor instead.
func (*NodeCounters) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{1}
}

func (x *NodeCounters) GetReceived() *NodeCountersSection {
	if x != nil {
		return x.Received
	}
	return nil
}

func (x *NodeCounters) GetProcessed() *NodeCountersSection {
	if x != nil {
		return x.Processed
	}
	return nil
}

func (x *NodeCounters) GetMissed() *NodeCountersSection {
	if x != nil {
		return x.Missed
	}
	return nil
}

func (x *NodeCounters) GetGenerated() *NodeCountersSection {
	if x != nil {
		return x.Generated
	}
	return nil
}

func (x *NodeCounters) GetOmitted() *NodeCountersSection {
	if x != nil {
		return x.Omitted
	}
	return nil
}

func (x *NodeCounters) GetSent() *NodeCountersSection {
	if x != nil {
		return x.Sent
	}
	return nil
}

type NodeCountersSection struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Packets       *NodeCountersSubSection `protobuf:"bytes,1,opt,name=packets,proto3" json:"packets,omitempty"`
	Frames        *NodeCountersSubSection `protobuf:"bytes,2,opt,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCountersSection) Reset() {
	*x = NodeCountersSection{}
	mi := &file_avpipeline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCountersSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCountersSection) ProtoMessage() {}

func (x *NodeCountersSection) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCountersSection.ProtoReflect.Descriptor instead.
func (*NodeCountersSection) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{2}
}

func (x *NodeCountersSection) GetPackets() *NodeCountersSubSection {
	if x != nil {
		return x.Packets
	}
	return nil
}

func (x *NodeCountersSection) GetFrames() *NodeCountersSubSection {
	if x != nil {
		return x.Frames
	}
	return nil
}

type NodeCountersSubSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unknown       *NodeCountersItem      `protobuf:"bytes,1,opt,name=unknown,proto3" json:"unknown,omitempty"`
	Other         *NodeCountersItem      `protobuf:"bytes,2,opt,name=other,proto3" json:"other,omitempty"`
	Video         *NodeCountersItem      `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`
	Audio         *NodeCountersItem      `protobuf:"bytes,4,opt,name=audio,proto3" json:"audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCountersSubSection) Reset() {
	*x = NodeCountersSubSection{}
	mi := &file_avpipeline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCountersSubSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCountersSubSection) ProtoMessage() {}

func (x *NodeCountersSubSection) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCountersSubSection.ProtoReflect.Descriptor instead.
func (*NodeCountersSubSection) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{3}
}

func (x *NodeCountersSubSection) GetUnknown() *NodeCountersItem {
	if x != nil {
		return x.Unknown
	}
	return nil
}

func (x *NodeCountersSubSection) GetOther() *NodeCountersItem {
	if x != nil {
		return x.Other
	}
	return nil
}

func (x *NodeCountersSubSection) GetVideo() *NodeCountersItem {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *NodeCountersSubSection) GetAudio() *NodeCountersItem {
	if x != nil {
		return x.Audio
	}
	return nil
}

type NodeCountersItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Bytes         uint64                 `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCountersItem) Reset() {
	*x = NodeCountersItem{}
	mi := &file_avpipeline_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCountersItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCountersItem) ProtoMessage() {}

func (x *NodeCountersItem) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCountersItem.ProtoReflect.Descriptor instead.
func (*NodeCountersItem) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{4}
}

func (x *NodeCountersItem) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *NodeCountersItem) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type Object struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_avpipeline_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{5}
}

func (x *Object) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Object) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Frame struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Frame          *libav.Frame           `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	CodecContext   *libav.CodecContext    `protobuf:"bytes,2,opt,name=codec_context,json=codecContext,proto3" json:"codec_context,omitempty"`
	StreamIndex    int32                  `protobuf:"varint,3,opt,name=stream_index,json=streamIndex,proto3" json:"stream_index,omitempty"`
	StreamsCount   int32                  `protobuf:"varint,4,opt,name=streams_count,json=streamsCount,proto3" json:"streams_count,omitempty"`
	StreamDuration int64                  `protobuf:"varint,5,opt,name=stream_duration,json=streamDuration,proto3" json:"stream_duration,omitempty"`
	TimeBase       *libav.Rational        `protobuf:"bytes,6,opt,name=time_base,json=timeBase,proto3" json:"time_base,omitempty"`
	Pos            int64                  `protobuf:"varint,7,opt,name=pos,proto3" json:"pos,omitempty"`
	Duration       int64                  `protobuf:"varint,8,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_avpipeline_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{6}
}

func (x *Frame) GetFrame() *libav.Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *Frame) GetCodecContext() *libav.CodecContext {
	if x != nil {
		return x.CodecContext
	}
	return nil
}

func (x *Frame) GetStreamIndex() int32 {
	if x != nil {
		return x.StreamIndex
	}
	return 0
}

func (x *Frame) GetStreamsCount() int32 {
	if x != nil {
		return x.StreamsCount
	}
	return 0
}

func (x *Frame) GetStreamDuration() int64 {
	if x != nil {
		return x.StreamDuration
	}
	return 0
}

func (x *Frame) GetTimeBase() *libav.Rational {
	if x != nil {
		return x.TimeBase
	}
	return nil
}

func (x *Frame) GetPos() int64 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *Frame) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type AutoBitrateCalculator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to AutoBitrateCalculator:
	//
	//	*AutoBitrateCalculator_Thresholds
	//	*AutoBitrateCalculator_LogK
	//	*AutoBitrateCalculator_Static
	//	*AutoBitrateCalculator_QueueSizeGapDecay
	AutoBitrateCalculator isAutoBitrateCalculator_AutoBitrateCalculator `protobuf_oneof:"auto_bitrate_calculator"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AutoBitrateCalculator) Reset() {
	*x = AutoBitrateCalculator{}
	mi := &file_avpipeline_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoBitrateCalculator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoBitrateCalculator) ProtoMessage() {}

func (x *AutoBitrateCalculator) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoBitrateCalculator.ProtoReflect.Descriptor instead.
func (*AutoBitrateCalculator) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{7}
}

func (x *AutoBitrateCalculator) GetAutoBitrateCalculator() isAutoBitrateCalculator_AutoBitrateCalculator {
	if x != nil {
		return x.AutoBitrateCalculator
	}
	return nil
}

func (x *AutoBitrateCalculator) GetThresholds() *AutoBitRateCalculatorThresholds {
	if x != nil {
		if x, ok := x.AutoBitrateCalculator.(*AutoBitrateCalculator_Thresholds); ok {
			return x.Thresholds
		}
	}
	return nil
}

func (x *AutoBitrateCalculator) GetLogK() *AutoBitrateCalculatorLogK {
	if x != nil {
		if x, ok := x.AutoBitrateCalculator.(*AutoBitrateCalculator_LogK); ok {
			return x.LogK
		}
	}
	return nil
}

func (x *AutoBitrateCalculator) GetStatic() uint64 {
	if x != nil {
		if x, ok := x.AutoBitrateCalculator.(*AutoBitrateCalculator_Static); ok {
			return x.Static
		}
	}
	return 0
}

func (x *AutoBitrateCalculator) GetQueueSizeGapDecay() *AutoBitrateCalculatorQueueSizeGapDecay {
	if x != nil {
		if x, ok := x.AutoBitrateCalculator.(*AutoBitrateCalculator_QueueSizeGapDecay); ok {
			return x.QueueSizeGapDecay
		}
	}
	return nil
}

type isAutoBitrateCalculator_AutoBitrateCalculator interface {
	isAutoBitrateCalculator_AutoBitrateCalculator()
}

type AutoBitrateCalculator_Thresholds struct {
	Thresholds *AutoBitRateCalculatorThresholds `protobuf:"bytes,1,opt,name=thresholds,proto3,oneof"`
}

type AutoBitrateCalculator_LogK struct {
	LogK *AutoBitrateCalculatorLogK `protobuf:"bytes,2,opt,name=log_k,json=logK,proto3,oneof"`
}

type AutoBitrateCalculator_Static struct {
	Static uint64 `protobuf:"varint,3,opt,name=static,proto3,oneof"`
}

type AutoBitrateCalculator_QueueSizeGapDecay struct {
	QueueSizeGapDecay *AutoBitrateCalculatorQueueSizeGapDecay `protobuf:"bytes,4,opt,name=queue_size_gap_decay,json=queueSizeGapDecay,proto3,oneof"`
}

func (*AutoBitrateCalculator_Thresholds) isAutoBitrateCalculator_AutoBitrateCalculator() {}

func (*AutoBitrateCalculator_LogK) isAutoBitrateCalculator_AutoBitrateCalculator() {}

func (*AutoBitrateCalculator_Static) isAutoBitrateCalculator_AutoBitrateCalculator() {}

func (*AutoBitrateCalculator_QueueSizeGapDecay) isAutoBitrateCalculator_AutoBitrateCalculator() {}

type AutoBitRateCalculatorThresholds struct {
	state                                  protoimpl.MessageState `protogen:"open.v1"`
	OutputExtremelyHighQueueSizeDurationMs uint64                 `protobuf:"varint,1,opt,name=output_extremely_high_queue_size_duration_ms,json=outputExtremelyHighQueueSizeDurationMs,proto3" json:"output_extremely_high_queue_size_duration_ms,omitempty"`
	OutputVeryHighQueueSizeDurationMs      uint64                 `protobuf:"varint,2,opt,name=output_very_high_queue_size_duration_ms,json=outputVeryHighQueueSizeDurationMs,proto3" json:"output_very_high_queue_size_duration_ms,omitempty"`
	OutputHighQueueSizeDurationMs          uint64                 `protobuf:"varint,3,opt,name=output_high_queue_size_duration_ms,json=outputHighQueueSizeDurationMs,proto3" json:"output_high_queue_size_duration_ms,omitempty"`
	OutputLowQueueSizeDurationMs           uint64                 `protobuf:"varint,4,opt,name=output_low_queue_size_duration_ms,json=outputLowQueueSizeDurationMs,proto3" json:"output_low_queue_size_duration_ms,omitempty"`
	OutputVeryLowQueueSizeDurationMs       uint64                 `protobuf:"varint,5,opt,name=output_very_low_queue_size_duration_ms,json=outputVeryLowQueueSizeDurationMs,proto3" json:"output_very_low_queue_size_duration_ms,omitempty"`
	IncreaseK                              float64                `protobuf:"fixed64,6,opt,name=increase_k,json=increaseK,proto3" json:"increase_k,omitempty"`
	DecreaseK                              float64                `protobuf:"fixed64,7,opt,name=decrease_k,json=decreaseK,proto3" json:"decrease_k,omitempty"`
	QuickIncreaseK                         float64                `protobuf:"fixed64,8,opt,name=quick_increase_k,json=quickIncreaseK,proto3" json:"quick_increase_k,omitempty"`
	QuickDecreaseK                         float64                `protobuf:"fixed64,9,opt,name=quick_decrease_k,json=quickDecreaseK,proto3" json:"quick_decrease_k,omitempty"`
	ExtremeDecreaseK                       float64                `protobuf:"fixed64,10,opt,name=extreme_decrease_k,json=extremeDecreaseK,proto3" json:"extreme_decrease_k,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *AutoBitRateCalculatorThresholds) Reset() {
	*x = AutoBitRateCalculatorThresholds{}
	mi := &file_avpipeline_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoBitRateCalculatorThresholds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoBitRateCalculatorThresholds) ProtoMessage() {}

func (x *AutoBitRateCalculatorThresholds) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoBitRateCalculatorThresholds.ProtoReflect.Descriptor instead.
func (*AutoBitRateCalculatorThresholds) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{8}
}

func (x *AutoBitRateCalculatorThresholds) GetOutputExtremelyHighQueueSizeDurationMs() uint64 {
	if x != nil {
		return x.OutputExtremelyHighQueueSizeDurationMs
	}
	return 0
}

func (x *AutoBitRateCalculatorThresholds) GetOutputVeryHighQueueSizeDurationMs() uint64 {
	if x != nil {
		return x.OutputVeryHighQueueSizeDurationMs
	}
	return 0
}

func (x *AutoBitRateCalculatorThresholds) GetOutputHighQueueSizeDurationMs() uint64 {
	if x != nil {
		return x.OutputHighQueueSizeDurationMs
	}
	return 0
}

func (x *AutoBitRateCalculatorThresholds) GetOutputLowQueueSizeDurationMs() uint64 {
	if x != nil {
		return x.OutputLowQueueSizeDurationMs
	}
	return 0
}

func (x *AutoBitRateCalculatorThresholds) GetOutputVeryLowQueueSizeDurationMs() uint64 {
	if x != nil {
		return x.OutputVeryLowQueueSizeDurationMs
	}
	return 0
}

func (x *AutoBitRateCalculatorThresholds) GetIncreaseK() float64 {
	if x != nil {
		return x.IncreaseK
	}
	return 0
}

func (x *AutoBitRateCalculatorThresholds) GetDecreaseK() float64 {
	if x != nil {
		return x.DecreaseK
	}
	return 0
}

func (x *AutoBitRateCalculatorThresholds) GetQuickIncreaseK() float64 {
	if x != nil {
		return x.QuickIncreaseK
	}
	return 0
}

func (x *AutoBitRateCalculatorThresholds) GetQuickDecreaseK() float64 {
	if x != nil {
		return x.QuickDecreaseK
	}
	return 0
}

func (x *AutoBitRateCalculatorThresholds) GetExtremeDecreaseK() float64 {
	if x != nil {
		return x.ExtremeDecreaseK
	}
	return 0
}

type MovingAverageConfigMAMA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FastLimit     float64                `protobuf:"fixed64,1,opt,name=fast_limit,json=fastLimit,proto3" json:"fast_limit,omitempty"`
	SlowLimit     float64                `protobuf:"fixed64,2,opt,name=slow_limit,json=slowLimit,proto3" json:"slow_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovingAverageConfigMAMA) Reset() {
	*x = MovingAverageConfigMAMA{}
	mi := &file_avpipeline_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovingAverageConfigMAMA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovingAverageConfigMAMA) ProtoMessage() {}

func (x *MovingAverageConfigMAMA) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovingAverageConfigMAMA.ProtoReflect.Descriptor instead.
func (*MovingAverageConfigMAMA) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{9}
}

func (x *MovingAverageConfigMAMA) GetFastLimit() float64 {
	if x != nil {
		return x.FastLimit
	}
	return 0
}

func (x *MovingAverageConfigMAMA) GetSlowLimit() float64 {
	if x != nil {
		return x.SlowLimit
	}
	return 0
}

type MovingAverageConfigOther struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonConfig    string                 `protobuf:"bytes,1,opt,name=json_config,json=jsonConfig,proto3" json:"json_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovingAverageConfigOther) Reset() {
	*x = MovingAverageConfigOther{}
	mi := &file_avpipeline_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovingAverageConfigOther) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovingAverageConfigOther) ProtoMessage() {}

func (x *MovingAverageConfigOther) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovingAverageConfigOther.ProtoReflect.Descriptor instead.
func (*MovingAverageConfigOther) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{10}
}

func (x *MovingAverageConfigOther) GetJsonConfig() string {
	if x != nil {
		return x.JsonConfig
	}
	return ""
}

type MovingAverageConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MovingAverageConfig:
	//
	//	*MovingAverageConfig_Mama
	//	*MovingAverageConfig_Other
	MovingAverageConfig isMovingAverageConfig_MovingAverageConfig `protobuf_oneof:"moving_average_config"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MovingAverageConfig) Reset() {
	*x = MovingAverageConfig{}
	mi := &file_avpipeline_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovingAverageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovingAverageConfig) ProtoMessage() {}

func (x *MovingAverageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovingAverageConfig.ProtoReflect.Descriptor instead.
func (*MovingAverageConfig) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{11}
}

func (x *MovingAverageConfig) GetMovingAverageConfig() isMovingAverageConfig_MovingAverageConfig {
	if x != nil {
		return x.MovingAverageConfig
	}
	return nil
}

func (x *MovingAverageConfig) GetMama() *MovingAverageConfigMAMA {
	if x != nil {
		if x, ok := x.MovingAverageConfig.(*MovingAverageConfig_Mama); ok {
			return x.Mama
		}
	}
	return nil
}

func (x *MovingAverageConfig) GetOther() *MovingAverageConfigOther {
	if x != nil {
		if x, ok := x.MovingAverageConfig.(*MovingAverageConfig_Other); ok {
			return x.Other
		}
	}
	return nil
}

type isMovingAverageConfig_MovingAverageConfig interface {
	isMovingAverageConfig_MovingAverageConfig()
}

type MovingAverageConfig_Mama struct {
	Mama *MovingAverageConfigMAMA `protobuf:"bytes,1,opt,name=mama,proto3,oneof"`
}

type MovingAverageConfig_Other struct {
	Other *MovingAverageConfigOther `protobuf:"bytes,65535,opt,name=other,proto3,oneof"`
}

func (*MovingAverageConfig_Mama) isMovingAverageConfig_MovingAverageConfig() {}

func (*MovingAverageConfig_Other) isMovingAverageConfig_MovingAverageConfig() {}

type Resolution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resolution) Reset() {
	*x = Resolution{}
	mi := &file_avpipeline_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resolution) ProtoMessage() {}

func (x *Resolution) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resolution.ProtoReflect.Descriptor instead.
func (*Resolution) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{12}
}

func (x *Resolution) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Resolution) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type FPSReductionRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BitrateMinBps uint64                 `protobuf:"varint,1,opt,name=bitrate_min_bps,json=bitrateMinBps,proto3" json:"bitrate_min_bps,omitempty"`
	BitrateMaxBps uint64                 `protobuf:"varint,2,opt,name=bitrate_max_bps,json=bitrateMaxBps,proto3" json:"bitrate_max_bps,omitempty"`
	FractionNum   uint32                 `protobuf:"varint,3,opt,name=fraction_num,json=fractionNum,proto3" json:"fraction_num,omitempty"`
	FractionDen   uint32                 `protobuf:"varint,4,opt,name=fraction_den,json=fractionDen,proto3" json:"fraction_den,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FPSReductionRange) Reset() {
	*x = FPSReductionRange{}
	mi := &file_avpipeline_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FPSReductionRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FPSReductionRange) ProtoMessage() {}

func (x *FPSReductionRange) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FPSReductionRange.ProtoReflect.Descriptor instead.
func (*FPSReductionRange) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{13}
}

func (x *FPSReductionRange) GetBitrateMinBps() uint64 {
	if x != nil {
		return x.BitrateMinBps
	}
	return 0
}

func (x *FPSReductionRange) GetBitrateMaxBps() uint64 {
	if x != nil {
		return x.BitrateMaxBps
	}
	return 0
}

func (x *FPSReductionRange) GetFractionNum() uint32 {
	if x != nil {
		return x.FractionNum
	}
	return 0
}

func (x *FPSReductionRange) GetFractionDen() uint32 {
	if x != nil {
		return x.FractionDen
	}
	return 0
}

type FPSReducerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ranges        []*FPSReductionRange   `protobuf:"bytes,1,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FPSReducerConfig) Reset() {
	*x = FPSReducerConfig{}
	mi := &file_avpipeline_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FPSReducerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FPSReducerConfig) ProtoMessage() {}

func (x *FPSReducerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FPSReducerConfig.ProtoReflect.Descriptor instead.
func (*FPSReducerConfig) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{14}
}

func (x *FPSReducerConfig) GetRanges() []*FPSReductionRange {
	if x != nil {
		return x.Ranges
	}
	return nil
}

type AutoBitRateResolutionAndBitRateConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Resolution     *Resolution            `protobuf:"bytes,1,opt,name=resolution,proto3" json:"resolution,omitempty"`
	BitrateHighBps uint64                 `protobuf:"varint,2,opt,name=bitrate_high_bps,json=bitrateHighBps,proto3" json:"bitrate_high_bps,omitempty"`
	BitrateLowBps  uint64                 `protobuf:"varint,3,opt,name=bitrate_low_bps,json=bitrateLowBps,proto3" json:"bitrate_low_bps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AutoBitRateResolutionAndBitRateConfig) Reset() {
	*x = AutoBitRateResolutionAndBitRateConfig{}
	mi := &file_avpipeline_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoBitRateResolutionAndBitRateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoBitRateResolutionAndBitRateConfig) ProtoMessage() {}

func (x *AutoBitRateResolutionAndBitRateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoBitRateResolutionAndBitRateConfig.ProtoReflect.Descriptor instead.
func (*AutoBitRateResolutionAndBitRateConfig) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{15}
}

func (x *AutoBitRateResolutionAndBitRateConfig) GetResolution() *Resolution {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *AutoBitRateResolutionAndBitRateConfig) GetBitrateHighBps() uint64 {
	if x != nil {
		return x.BitrateHighBps
	}
	return 0
}

func (x *AutoBitRateResolutionAndBitRateConfig) GetBitrateLowBps() uint64 {
	if x != nil {
		return x.BitrateLowBps
	}
	return 0
}

type AutoBitRateResolutionAndBitRateConfigs struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Configs       []*AutoBitRateResolutionAndBitRateConfig `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoBitRateResolutionAndBitRateConfigs) Reset() {
	*x = AutoBitRateResolutionAndBitRateConfigs{}
	mi := &file_avpipeline_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoBitRateResolutionAndBitRateConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoBitRateResolutionAndBitRateConfigs) ProtoMessage() {}

func (x *AutoBitRateResolutionAndBitRateConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoBitRateResolutionAndBitRateConfigs.ProtoReflect.Descriptor instead.
func (*AutoBitRateResolutionAndBitRateConfigs) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{16}
}

func (x *AutoBitRateResolutionAndBitRateConfigs) GetConfigs() []*AutoBitRateResolutionAndBitRateConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type AutoBitRateVideoConfig struct {
	state                                 protoimpl.MessageState                  `protogen:"open.v1"`
	ResolutionsAndBitRates                *AutoBitRateResolutionAndBitRateConfigs `protobuf:"bytes,1,opt,name=resolutions_and_bit_rates,json=resolutionsAndBitRates,proto3" json:"resolutions_and_bit_rates,omitempty"`
	Calculator                            *AutoBitrateCalculator                  `protobuf:"bytes,2,opt,name=calculator,proto3" json:"calculator,omitempty"`
	FpsReducer                            *FPSReducerConfig                       `protobuf:"bytes,3,opt,name=fps_reducer,json=fpsReducer,proto3" json:"fps_reducer,omitempty"`
	CheckIntervalMs                       uint64                                  `protobuf:"varint,4,opt,name=check_interval_ms,json=checkIntervalMs,proto3" json:"check_interval_ms,omitempty"`
	AutoByPass                            bool                                    `protobuf:"varint,5,opt,name=auto_by_pass,json=autoByPass,proto3" json:"auto_by_pass,omitempty"`
	MaxBitRateBps                         uint64                                  `protobuf:"varint,6,opt,name=max_bit_rate_bps,json=maxBitRateBps,proto3" json:"max_bit_rate_bps,omitempty"`
	MinBitRateBps                         uint64                                  `protobuf:"varint,7,opt,name=min_bit_rate_bps,json=minBitRateBps,proto3" json:"min_bit_rate_bps,omitempty"`
	BitRateIncreaseSlowdownMs             uint64                                  `protobuf:"varint,8,opt,name=bit_rate_increase_slowdown_ms,json=bitRateIncreaseSlowdownMs,proto3" json:"bit_rate_increase_slowdown_ms,omitempty"`
	ResolutionSlowdownDurationUpgradeMs   uint64                                  `protobuf:"varint,9,opt,name=resolution_slowdown_duration_upgrade_ms,json=resolutionSlowdownDurationUpgradeMs,proto3" json:"resolution_slowdown_duration_upgrade_ms,omitempty"`
	ResolutionSlowdownDurationDowngradeMs uint64                                  `protobuf:"varint,10,opt,name=resolution_slowdown_duration_downgrade_ms,json=resolutionSlowdownDurationDowngradeMs,proto3" json:"resolution_slowdown_duration_downgrade_ms,omitempty"`
	MinResolution                         *Resolution                             `protobuf:"bytes,11,opt,name=min_resolution,json=minResolution,proto3" json:"min_resolution,omitempty"`
	MaxResolution                         *Resolution                             `protobuf:"bytes,12,opt,name=max_resolution,json=maxResolution,proto3" json:"max_resolution,omitempty"`
	MinFpsFraction                        float64                                 `protobuf:"fixed64,13,opt,name=min_fps_fraction,json=minFpsFraction,proto3" json:"min_fps_fraction,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *AutoBitRateVideoConfig) Reset() {
	*x = AutoBitRateVideoConfig{}
	mi := &file_avpipeline_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoBitRateVideoConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoBitRateVideoConfig) ProtoMessage() {}

func (x *AutoBitRateVideoConfig) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoBitRateVideoConfig.ProtoReflect.Descriptor instead.
func (*AutoBitRateVideoConfig) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{17}
}

func (x *AutoBitRateVideoConfig) GetResolutionsAndBitRates() *AutoBitRateResolutionAndBitRateConfigs {
	if x != nil {
		return x.ResolutionsAndBitRates
	}
	return nil
}

func (x *AutoBitRateVideoConfig) GetCalculator() *AutoBitrateCalculator {
	if x != nil {
		return x.Calculator
	}
	return nil
}

func (x *AutoBitRateVideoConfig) GetFpsReducer() *FPSReducerConfig {
	if x != nil {
		return x.FpsReducer
	}
	return nil
}

func (x *AutoBitRateVideoConfig) GetCheckIntervalMs() uint64 {
	if x != nil {
		return x.CheckIntervalMs
	}
	return 0
}

func (x *AutoBitRateVideoConfig) GetAutoByPass() bool {
	if x != nil {
		return x.AutoByPass
	}
	return false
}

func (x *AutoBitRateVideoConfig) GetMaxBitRateBps() uint64 {
	if x != nil {
		return x.MaxBitRateBps
	}
	return 0
}

func (x *AutoBitRateVideoConfig) GetMinBitRateBps() uint64 {
	if x != nil {
		return x.MinBitRateBps
	}
	return 0
}

func (x *AutoBitRateVideoConfig) GetBitRateIncreaseSlowdownMs() uint64 {
	if x != nil {
		return x.BitRateIncreaseSlowdownMs
	}
	return 0
}

func (x *AutoBitRateVideoConfig) GetResolutionSlowdownDurationUpgradeMs() uint64 {
	if x != nil {
		return x.ResolutionSlowdownDurationUpgradeMs
	}
	return 0
}

func (x *AutoBitRateVideoConfig) GetResolutionSlowdownDurationDowngradeMs() uint64 {
	if x != nil {
		return x.ResolutionSlowdownDurationDowngradeMs
	}
	return 0
}

func (x *AutoBitRateVideoConfig) GetMinResolution() *Resolution {
	if x != nil {
		return x.MinResolution
	}
	return nil
}

func (x *AutoBitRateVideoConfig) GetMaxResolution() *Resolution {
	if x != nil {
		return x.MaxResolution
	}
	return nil
}

func (x *AutoBitRateVideoConfig) GetMinFpsFraction() float64 {
	if x != nil {
		return x.MinFpsFraction
	}
	return 0
}

type AutoBitrateCalculatorLogK struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueueOptimalMs uint64                 `protobuf:"varint,1,opt,name=queue_optimal_ms,json=queueOptimalMs,proto3" json:"queue_optimal_ms,omitempty"`
	Inertia        float64                `protobuf:"fixed64,2,opt,name=inertia,proto3" json:"inertia,omitempty"` // [0.0..1.0]
	MovingAverage  *MovingAverageConfig   `protobuf:"bytes,3,opt,name=moving_average,json=movingAverage,proto3" json:"moving_average,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AutoBitrateCalculatorLogK) Reset() {
	*x = AutoBitrateCalculatorLogK{}
	mi := &file_avpipeline_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoBitrateCalculatorLogK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoBitrateCalculatorLogK) ProtoMessage() {}

func (x *AutoBitrateCalculatorLogK) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoBitrateCalculatorLogK.ProtoReflect.Descriptor instead.
func (*AutoBitrateCalculatorLogK) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{18}
}

func (x *AutoBitrateCalculatorLogK) GetQueueOptimalMs() uint64 {
	if x != nil {
		return x.QueueOptimalMs
	}
	return 0
}

func (x *AutoBitrateCalculatorLogK) GetInertia() float64 {
	if x != nil {
		return x.Inertia
	}
	return 0
}

func (x *AutoBitrateCalculatorLogK) GetMovingAverage() *MovingAverageConfig {
	if x != nil {
		return x.MovingAverage
	}
	return nil
}

type AutoBitrateCalculatorQueueSizeGapDecay struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	QueueOptimalMs     uint64                 `protobuf:"varint,1,opt,name=queue_optimal_ms,json=queueOptimalMs,proto3" json:"queue_optimal_ms,omitempty"`
	QueueSizeMin       uint64                 `protobuf:"varint,2,opt,name=queue_size_min,json=queueSizeMin,proto3" json:"queue_size_min,omitempty"`
	GapDecayMs         uint64                 `protobuf:"varint,3,opt,name=gap_decay_ms,json=gapDecayMs,proto3" json:"gap_decay_ms,omitempty"`
	IncreaseInertiaMs  uint64                 `protobuf:"varint,4,opt,name=increase_inertia_ms,json=increaseInertiaMs,proto3" json:"increase_inertia_ms,omitempty"`
	DerivativeSmoothed *MovingAverageConfig   `protobuf:"bytes,5,opt,name=derivative_smoothed,json=derivativeSmoothed,proto3" json:"derivative_smoothed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AutoBitrateCalculatorQueueSizeGapDecay) Reset() {
	*x = AutoBitrateCalculatorQueueSizeGapDecay{}
	mi := &file_avpipeline_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoBitrateCalculatorQueueSizeGapDecay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoBitrateCalculatorQueueSizeGapDecay) ProtoMessage() {}

func (x *AutoBitrateCalculatorQueueSizeGapDecay) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoBitrateCalculatorQueueSizeGapDecay.ProtoReflect.Descriptor instead.
func (*AutoBitrateCalculatorQueueSizeGapDecay) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{19}
}

func (x *AutoBitrateCalculatorQueueSizeGapDecay) GetQueueOptimalMs() uint64 {
	if x != nil {
		return x.QueueOptimalMs
	}
	return 0
}

func (x *AutoBitrateCalculatorQueueSizeGapDecay) GetQueueSizeMin() uint64 {
	if x != nil {
		return x.QueueSizeMin
	}
	return 0
}

func (x *AutoBitrateCalculatorQueueSizeGapDecay) GetGapDecayMs() uint64 {
	if x != nil {
		return x.GapDecayMs
	}
	return 0
}

func (x *AutoBitrateCalculatorQueueSizeGapDecay) GetIncreaseInertiaMs() uint64 {
	if x != nil {
		return x.IncreaseInertiaMs
	}
	return 0
}

func (x *AutoBitrateCalculatorQueueSizeGapDecay) GetDerivativeSmoothed() *MovingAverageConfig {
	if x != nil {
		return x.DerivativeSmoothed
	}
	return nil
}

type MonitorRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NodeId               uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EventType            MonitorEventType       `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=avpipeline.MonitorEventType" json:"event_type,omitempty"`
	IncludePacketPayload bool                   `protobuf:"varint,3,opt,name=include_packet_payload,json=includePacketPayload,proto3" json:"include_packet_payload,omitempty"`
	IncludeFramePayload  bool                   `protobuf:"varint,4,opt,name=include_frame_payload,json=includeFramePayload,proto3" json:"include_frame_payload,omitempty"`
	DoDecode             bool                   `protobuf:"varint,5,opt,name=do_decode,json=doDecode,proto3" json:"do_decode,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MonitorRequest) Reset() {
	*x = MonitorRequest{}
	mi := &file_avpipeline_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorRequest) ProtoMessage() {}

func (x *MonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorRequest.ProtoReflect.Descriptor instead.
func (*MonitorRequest) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{20}
}

func (x *MonitorRequest) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *MonitorRequest) GetEventType() MonitorEventType {
	if x != nil {
		return x.EventType
	}
	return MonitorEventType_UNDEFINED_EVENT_TYPE
}

func (x *MonitorRequest) GetIncludePacketPayload() bool {
	if x != nil {
		return x.IncludePacketPayload
	}
	return false
}

func (x *MonitorRequest) GetIncludeFramePayload() bool {
	if x != nil {
		return x.IncludeFramePayload
	}
	return false
}

func (x *MonitorRequest) GetDoDecode() bool {
	if x != nil {
		return x.DoDecode
	}
	return false
}

type MonitorEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs      uint64                 `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	SourceKernelId   uint64                 `protobuf:"varint,2,opt,name=source_kernel_id,json=sourceKernelId,proto3" json:"source_kernel_id,omitempty"`
	Stream           *libav.Stream          `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`
	Packet           *libav.Packet          `protobuf:"bytes,4,opt,name=packet,proto3,oneof" json:"packet,omitempty"`
	Frames           []*libav.Frame         `protobuf:"bytes,5,rep,name=frames,proto3" json:"frames,omitempty"`
	PipelineSideData []byte                 `protobuf:"bytes,6,opt,name=pipeline_side_data,json=pipelineSideData,proto3" json:"pipeline_side_data,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MonitorEvent) Reset() {
	*x = MonitorEvent{}
	mi := &file_avpipeline_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorEvent) ProtoMessage() {}

func (x *MonitorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorEvent.ProtoReflect.Descriptor instead.
func (*MonitorEvent) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{21}
}

func (x *MonitorEvent) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *MonitorEvent) GetSourceKernelId() uint64 {
	if x != nil {
		return x.SourceKernelId
	}
	return 0
}

func (x *MonitorEvent) GetStream() *libav.Stream {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *MonitorEvent) GetPacket() *libav.Packet {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *MonitorEvent) GetFrames() []*libav.Frame {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *MonitorEvent) GetPipelineSideData() []byte {
	if x != nil {
		return x.PipelineSideData
	}
	return nil
}

type CustomOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomOption) Reset() {
	*x = CustomOption{}
	mi := &file_avpipeline_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomOption) ProtoMessage() {}

func (x *CustomOption) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomOption.ProtoReflect.Descriptor instead.
func (*CustomOption) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{22}
}

func (x *CustomOption) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CustomOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type InputConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AsyncOpen          bool                   `protobuf:"varint,1,opt,name=async_open,json=asyncOpen,proto3" json:"async_open,omitempty"`
	AutoClose          bool                   `protobuf:"varint,2,opt,name=auto_close,json=autoClose,proto3" json:"auto_close,omitempty"`
	RecvBufferSize     uint32                 `protobuf:"varint,3,opt,name=recv_buffer_size,json=recvBufferSize,proto3" json:"recv_buffer_size,omitempty"`
	ForceRealTime      *bool                  `protobuf:"varint,4,opt,name=force_real_time,json=forceRealTime,proto3,oneof" json:"force_real_time,omitempty"`
	ForceStartPts      *int64                 `protobuf:"varint,5,opt,name=force_start_pts,json=forceStartPts,proto3,oneof" json:"force_start_pts,omitempty"`
	ForceStartDts      *int64                 `protobuf:"varint,6,opt,name=force_start_dts,json=forceStartDts,proto3,oneof" json:"force_start_dts,omitempty"`
	IgnoreIncorrectDts bool                   `protobuf:"varint,7,opt,name=ignore_incorrect_dts,json=ignoreIncorrectDts,proto3" json:"ignore_incorrect_dts,omitempty"`
	IgnoreZeroDuration bool                   `protobuf:"varint,8,opt,name=ignore_zero_duration,json=ignoreZeroDuration,proto3" json:"ignore_zero_duration,omitempty"`
	CustomOptions      []*CustomOption        `protobuf:"bytes,9,rep,name=custom_options,json=customOptions,proto3" json:"custom_options,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InputConfig) Reset() {
	*x = InputConfig{}
	mi := &file_avpipeline_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputConfig) ProtoMessage() {}

func (x *InputConfig) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputConfig.ProtoReflect.Descriptor instead.
func (*InputConfig) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{23}
}

func (x *InputConfig) GetAsyncOpen() bool {
	if x != nil {
		return x.AsyncOpen
	}
	return false
}

func (x *InputConfig) GetAutoClose() bool {
	if x != nil {
		return x.AutoClose
	}
	return false
}

func (x *InputConfig) GetRecvBufferSize() uint32 {
	if x != nil {
		return x.RecvBufferSize
	}
	return 0
}

func (x *InputConfig) GetForceRealTime() bool {
	if x != nil && x.ForceRealTime != nil {
		return *x.ForceRealTime
	}
	return false
}

func (x *InputConfig) GetForceStartPts() int64 {
	if x != nil && x.ForceStartPts != nil {
		return *x.ForceStartPts
	}
	return 0
}

func (x *InputConfig) GetForceStartDts() int64 {
	if x != nil && x.ForceStartDts != nil {
		return *x.ForceStartDts
	}
	return 0
}

func (x *InputConfig) GetIgnoreIncorrectDts() bool {
	if x != nil {
		return x.IgnoreIncorrectDts
	}
	return false
}

func (x *InputConfig) GetIgnoreZeroDuration() bool {
	if x != nil {
		return x.IgnoreZeroDuration
	}
	return false
}

func (x *InputConfig) GetCustomOptions() []*CustomOption {
	if x != nil {
		return x.CustomOptions
	}
	return nil
}

var File_avpipeline_proto protoreflect.FileDescriptor

const file_avpipeline_proto_rawDesc = "" +
	"\n" +
	"\x10avpipeline.proto\x12\n" +
	"avpipeline\x1a\vlibav.proto\"\xd1\x02\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"is_serving\x18\x04 \x01(\bR\tisServing\x124\n" +
	"\bcounters\x18\x05 \x01(\v2\x18.avpipeline.NodeCountersR\bcounters\x12D\n" +
	"\x15todo_publishing_nodes\x18\x06 \x03(\v2\x10.avpipeline.NodeR\x13todoPublishingNodes\x129\n" +
	"\x0fconsuming_nodes\x18\a \x03(\v2\x10.avpipeline.NodeR\x0econsumingNodes\x12-\n" +
	"\x13first_frame_unix_ns\x18\b \x01(\x03R\x10firstFrameUnixNs\"\xf2\x02\n" +
	"\fNodeCounters\x12;\n" +
	"\breceived\x18\x01 \x01(\v2\x1f.avpipeline.NodeCountersSectionR\breceived\x12=\n" +
	"\tprocessed\x18\x02 \x01(\v2\x1f.avpipeline.NodeCountersSectionR\tprocessed\x127\n" +
	"\x06missed\x18\x03 \x01(\v2\x1f.avpipeline.NodeCountersSectionR\x06missed\x12=\n" +
	"\tgenerated\x18\x04 \x01(\v2\x1f.avpipeline.NodeCountersSectionR\tgenerated\x129\n" +
	"\aomitted\x18\x05 \x01(\v2\x1f.avpipeline.NodeCountersSectionR\aomitted\x123\n" +
	"\x04sent\x18\x06 \x01(\v2\x1f.avpipeline.NodeCountersSectionR\x04sent\"\x8f\x01\n" +
	"\x13NodeCountersSection\x12<\n" +
	"\apackets\x18\x01 \x01(\v2\".avpipeline.NodeCountersSubSectionR\apackets\x12:\n" +
	"\x06frames\x18\x02 \x01(\v2\".avpipeline.NodeCountersSubSectionR\x06frames\"\xec\x01\n" +
	"\x16NodeCountersSubSection\x126\n" +
	"\aunknown\x18\x01 \x01(\v2\x1c.avpipeline.NodeCountersItemR\aunknown\x122\n" +
	"\x05other\x18\x02 \x01(\v2\x1c.avpipeline.NodeCountersItemR\x05other\x122\n" +
	"\x05video\x18\x03 \x01(\v2\x1c.avpipeline.NodeCountersItemR\x05video\x122\n" +
	"\x05audio\x18\x04 \x01(\v2\x1c.avpipeline.NodeCountersItemR\x05audio\">\n" +
	"\x10NodeCountersItem\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x04R\x05bytes\"0\n" +
	"\x06Object\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xb2\x02\n" +
	"\x05Frame\x12\"\n" +
	"\x05frame\x18\x01 \x01(\v2\f.libav.FrameR\x05frame\x128\n" +
	"\rcodec_context\x18\x02 \x01(\v2\x13.libav.CodecContextR\fcodecContext\x12!\n" +
	"\fstream_index\x18\x03 \x01(\x05R\vstreamIndex\x12#\n" +
	"\rstreams_count\x18\x04 \x01(\x05R\fstreamsCount\x12'\n" +
	"\x0fstream_duration\x18\x05 \x01(\x03R\x0estreamDuration\x12,\n" +
	"\ttime_base\x18\x06 \x01(\v2\x0f.libav.RationalR\btimeBase\x12\x10\n" +
	"\x03pos\x18\a \x01(\x03R\x03pos\x12\x1a\n" +
	"\bduration\x18\b \x01(\x03R\bduration\"\xc0\x02\n" +
	"\x15AutoBitrateCalculator\x12M\n" +
	"\n" +
	"thresholds\x18\x01 \x01(\v2+.avpipeline.AutoBitRateCalculatorThresholdsH\x00R\n" +
	"thresholds\x12<\n" +
	"\x05log_k\x18\x02 \x01(\v2%.avpipeline.AutoBitrateCalculatorLogKH\x00R\x04logK\x12\x18\n" +
	"\x06static\x18\x03 \x01(\x04H\x00R\x06static\x12e\n" +
	"\x14queue_size_gap_decay\x18\x04 \x01(\v22.avpipeline.AutoBitrateCalculatorQueueSizeGapDecayH\x00R\x11queueSizeGapDecayB\x19\n" +
	"\x17auto_bitrate_calculator\"\xf9\x04\n" +
	"\x1fAutoBitRateCalculatorThresholds\x12\\\n" +
	",output_extremely_high_queue_size_duration_ms\x18\x01 \x01(\x04R&outputExtremelyHighQueueSizeDurationMs\x12R\n" +
	"'output_very_high_queue_size_duration_ms\x18\x02 \x01(\x04R!outputVeryHighQueueSizeDurationMs\x12I\n" +
	"\"output_high_queue_size_duration_ms\x18\x03 \x01(\x04R\x1doutputHighQueueSizeDurationMs\x12G\n" +
	"!output_low_queue_size_duration_ms\x18\x04 \x01(\x04R\x1coutputLowQueueSizeDurationMs\x12P\n" +
	"&output_very_low_queue_size_duration_ms\x18\x05 \x01(\x04R outputVeryLowQueueSizeDurationMs\x12\x1d\n" +
	"\n" +
	"increase_k\x18\x06 \x01(\x01R\tincreaseK\x12\x1d\n" +
	"\n" +
	"decrease_k\x18\a \x01(\x01R\tdecreaseK\x12(\n" +
	"\x10quick_increase_k\x18\b \x01(\x01R\x0equickIncreaseK\x12(\n" +
	"\x10quick_decrease_k\x18\t \x01(\x01R\x0equickDecreaseK\x12,\n" +
	"\x12extreme_decrease_k\x18\n" +
	" \x01(\x01R\x10extremeDecreaseK\"W\n" +
	"\x17MovingAverageConfigMAMA\x12\x1d\n" +
	"\n" +
	"fast_limit\x18\x01 \x01(\x01R\tfastLimit\x12\x1d\n" +
	"\n" +
	"slow_limit\x18\x02 \x01(\x01R\tslowLimit\";\n" +
	"\x18MovingAverageConfigOther\x12\x1f\n" +
	"\vjson_config\x18\x01 \x01(\tR\n" +
	"jsonConfig\"\xa9\x01\n" +
	"\x13MovingAverageConfig\x129\n" +
	"\x04mama\x18\x01 \x01(\v2#.avpipeline.MovingAverageConfigMAMAH\x00R\x04mama\x12>\n" +
	"\x05other\x18\xff\xff\x03 \x01(\v2$.avpipeline.MovingAverageConfigOtherH\x00R\x05otherB\x17\n" +
	"\x15moving_average_config\":\n" +
	"\n" +
	"Resolution\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\"\xa9\x01\n" +
	"\x11FPSReductionRange\x12&\n" +
	"\x0fbitrate_min_bps\x18\x01 \x01(\x04R\rbitrateMinBps\x12&\n" +
	"\x0fbitrate_max_bps\x18\x02 \x01(\x04R\rbitrateMaxBps\x12!\n" +
	"\ffraction_num\x18\x03 \x01(\rR\vfractionNum\x12!\n" +
	"\ffraction_den\x18\x04 \x01(\rR\vfractionDen\"I\n" +
	"\x10FPSReducerConfig\x125\n" +
	"\x06ranges\x18\x01 \x03(\v2\x1d.avpipeline.FPSReductionRangeR\x06ranges\"\xb1\x01\n" +
	"%AutoBitRateResolutionAndBitRateConfig\x126\n" +
	"\n" +
	"resolution\x18\x01 \x01(\v2\x16.avpipeline.ResolutionR\n" +
	"resolution\x12(\n" +
	"\x10bitrate_high_bps\x18\x02 \x01(\x04R\x0ebitrateHighBps\x12&\n" +
	"\x0fbitrate_low_bps\x18\x03 \x01(\x04R\rbitrateLowBps\"u\n" +
	"&AutoBitRateResolutionAndBitRateConfigs\x12K\n" +
	"\aconfigs\x18\x01 \x03(\v21.avpipeline.AutoBitRateResolutionAndBitRateConfigR\aconfigs\"\xc3\x06\n" +
	"\x16AutoBitRateVideoConfig\x12m\n" +
	"\x19resolutions_and_bit_rates\x18\x01 \x01(\v22.avpipeline.AutoBitRateResolutionAndBitRateConfigsR\x16resolutionsAndBitRates\x12A\n" +
	"\n" +
	"calculator\x18\x02 \x01(\v2!.avpipeline.AutoBitrateCalculatorR\n" +
	"calculator\x12=\n" +
	"\vfps_reducer\x18\x03 \x01(\v2\x1c.avpipeline.FPSReducerConfigR\n" +
	"fpsReducer\x12*\n" +
	"\x11check_interval_ms\x18\x04 \x01(\x04R\x0fcheckIntervalMs\x12 \n" +
	"\fauto_by_pass\x18\x05 \x01(\bR\n" +
	"autoByPass\x12'\n" +
	"\x10max_bit_rate_bps\x18\x06 \x01(\x04R\rmaxBitRateBps\x12'\n" +
	"\x10min_bit_rate_bps\x18\a \x01(\x04R\rminBitRateBps\x12@\n" +
	"\x1dbit_rate_increase_slowdown_ms\x18\b \x01(\x04R\x19bitRateIncreaseSlowdownMs\x12T\n" +
	"'resolution_slowdown_duration_upgrade_ms\x18\t \x01(\x04R#resolutionSlowdownDurationUpgradeMs\x12X\n" +
	")resolution_slowdown_duration_downgrade_ms\x18\n" +
	" \x01(\x04R%resolutionSlowdownDurationDowngradeMs\x12=\n" +
	"\x0emin_resolution\x18\v \x01(\v2\x16.avpipeline.ResolutionR\rminResolution\x12=\n" +
	"\x0emax_resolution\x18\f \x01(\v2\x16.avpipeline.ResolutionR\rmaxResolution\x12(\n" +
	"\x10min_fps_fraction\x18\r \x01(\x01R\x0eminFpsFraction\"\xa7\x01\n" +
	"\x19AutoBitrateCalculatorLogK\x12(\n" +
	"\x10queue_optimal_ms\x18\x01 \x01(\x04R\x0equeueOptimalMs\x12\x18\n" +
	"\ainertia\x18\x02 \x01(\x01R\ainertia\x12F\n" +
	"\x0emoving_average\x18\x03 \x01(\v2\x1f.avpipeline.MovingAverageConfigR\rmovingAverage\"\x9c\x02\n" +
	"&AutoBitrateCalculatorQueueSizeGapDecay\x12(\n" +
	"\x10queue_optimal_ms\x18\x01 \x01(\x04R\x0equeueOptimalMs\x12$\n" +
	"\x0equeue_size_min\x18\x02 \x01(\x04R\fqueueSizeMin\x12 \n" +
	"\fgap_decay_ms\x18\x03 \x01(\x04R\n" +
	"gapDecayMs\x12.\n" +
	"\x13increase_inertia_ms\x18\x04 \x01(\x04R\x11increaseInertiaMs\x12P\n" +
	"\x13derivative_smoothed\x18\x05 \x01(\v2\x1f.avpipeline.MovingAverageConfigR\x12derivativeSmoothed\"\xed\x01\n" +
	"\x0eMonitorRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12;\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x1c.avpipeline.MonitorEventTypeR\teventType\x124\n" +
	"\x16include_packet_payload\x18\x03 \x01(\bR\x14includePacketPayload\x122\n" +
	"\x15include_frame_payload\x18\x04 \x01(\bR\x13includeFramePayload\x12\x1b\n" +
	"\tdo_decode\x18\x05 \x01(\bR\bdoDecode\"\x8d\x02\n" +
	"\fMonitorEvent\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x04R\vtimestampNs\x12(\n" +
	"\x10source_kernel_id\x18\x02 \x01(\x04R\x0esourceKernelId\x12%\n" +
	"\x06stream\x18\x03 \x01(\v2\r.libav.StreamR\x06stream\x12*\n" +
	"\x06packet\x18\x04 \x01(\v2\r.libav.PacketH\x00R\x06packet\x88\x01\x01\x12$\n" +
	"\x06frames\x18\x05 \x03(\v2\f.libav.FrameR\x06frames\x12,\n" +
	"\x12pipeline_side_data\x18\x06 \x01(\fR\x10pipelineSideDataB\t\n" +
	"\a_packet\"6\n" +
	"\fCustomOption\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xdd\x03\n" +
	"\vInputConfig\x12\x1d\n" +
	"\n" +
	"async_open\x18\x01 \x01(\bR\tasyncOpen\x12\x1d\n" +
	"\n" +
	"auto_close\x18\x02 \x01(\bR\tautoClose\x12(\n" +
	"\x10recv_buffer_size\x18\x03 \x01(\rR\x0erecvBufferSize\x12+\n" +
	"\x0fforce_real_time\x18\x04 \x01(\bH\x00R\rforceRealTime\x88\x01\x01\x12+\n" +
	"\x0fforce_start_pts\x18\x05 \x01(\x03H\x01R\rforceStartPts\x88\x01\x01\x12+\n" +
	"\x0fforce_start_dts\x18\x06 \x01(\x03H\x02R\rforceStartDts\x88\x01\x01\x120\n" +
	"\x14ignore_incorrect_dts\x18\a \x01(\bR\x12ignoreIncorrectDts\x120\n" +
	"\x14ignore_zero_duration\x18\b \x01(\bR\x12ignoreZeroDuration\x12?\n" +
	"\x0ecustom_options\x18\t \x03(\v2\x18.avpipeline.CustomOptionR\rcustomOptionsB\x12\n" +
	"\x10_force_real_timeB\x12\n" +
	"\x10_force_start_ptsB\x12\n" +
	"\x10_force_start_dts*}\n" +
	"\x10MonitorEventType\x12\x18\n" +
	"\x14UNDEFINED_EVENT_TYPE\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_RECEIVE\x10\x01\x12\x13\n" +
	"\x0fEVENT_TYPE_SEND\x10\x02\x12\"\n" +
	"\x1dEVENT_TYPE_KERNEL_OUTPUT_SEND\x10\x80\x01BBZ@github.com/xaionaro-go/avpipeline/protobuf/avpipeline;avpipelineb\x06proto3"

var (
	file_avpipeline_proto_rawDescOnce sync.Once
	file_avpipeline_proto_rawDescData []byte
)

func file_avpipeline_proto_rawDescGZIP() []byte {
	file_avpipeline_proto_rawDescOnce.Do(func() {
		file_avpipeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avpipeline_proto_rawDesc), len(file_avpipeline_proto_rawDesc)))
	})
	return file_avpipeline_proto_rawDescData
}

var file_avpipeline_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_avpipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_avpipeline_proto_goTypes = []any{
	(MonitorEventType)(0),                          // 0: avpipeline.MonitorEventType
	(*Node)(nil),                                   // 1: avpipeline.Node
	(*NodeCounters)(nil),                           // 2: avpipeline.NodeCounters
	(*NodeCountersSection)(nil),                    // 3: avpipeline.NodeCountersSection
	(*NodeCountersSubSection)(nil),                 // 4: avpipeline.NodeCountersSubSection
	(*NodeCountersItem)(nil),                       // 5: avpipeline.NodeCountersItem
	(*Object)(nil),                                 // 6: avpipeline.Object
	(*Frame)(nil),                                  // 7: avpipeline.Frame
	(*AutoBitrateCalculator)(nil),                  // 8: avpipeline.AutoBitrateCalculator
	(*AutoBitRateCalculatorThresholds)(nil),        // 9: avpipeline.AutoBitRateCalculatorThresholds
	(*MovingAverageConfigMAMA)(nil),                // 10: avpipeline.MovingAverageConfigMAMA
	(*MovingAverageConfigOther)(nil),               // 11: avpipeline.MovingAverageConfigOther
	(*MovingAverageConfig)(nil),                    // 12: avpipeline.MovingAverageConfig
	(*Resolution)(nil),                             // 13: avpipeline.Resolution
	(*FPSReductionRange)(nil),                      // 14: avpipeline.FPSReductionRange
	(*FPSReducerConfig)(nil),                       // 15: avpipeline.FPSReducerConfig
	(*AutoBitRateResolutionAndBitRateConfig)(nil),  // 16: avpipeline.AutoBitRateResolutionAndBitRateConfig
	(*AutoBitRateResolutionAndBitRateConfigs)(nil), // 17: avpipeline.AutoBitRateResolutionAndBitRateConfigs
	(*AutoBitRateVideoConfig)(nil),                 // 18: avpipeline.AutoBitRateVideoConfig
	(*AutoBitrateCalculatorLogK)(nil),              // 19: avpipeline.AutoBitrateCalculatorLogK
	(*AutoBitrateCalculatorQueueSizeGapDecay)(nil), // 20: avpipeline.AutoBitrateCalculatorQueueSizeGapDecay
	(*MonitorRequest)(nil),                         // 21: avpipeline.MonitorRequest
	(*MonitorEvent)(nil),                           // 22: avpipeline.MonitorEvent
	(*CustomOption)(nil),                           // 23: avpipeline.CustomOption
	(*InputConfig)(nil),                            // 24: avpipeline.InputConfig
	(*libav.Frame)(nil),                            // 25: libav.Frame
	(*libav.CodecContext)(nil),                     // 26: libav.CodecContext
	(*libav.Rational)(nil),                         // 27: libav.Rational
	(*libav.Stream)(nil),                           // 28: libav.Stream
	(*libav.Packet)(nil),                           // 29: libav.Packet
}
var file_avpipeline_proto_depIdxs = []int32{
	2,  // 0: avpipeline.Node.counters:type_name -> avpipeline.NodeCounters
	1,  // 1: avpipeline.Node.todo_publishing_nodes:type_name -> avpipeline.Node
	1,  // 2: avpipeline.Node.consuming_nodes:type_name -> avpipeline.Node
	3,  // 3: avpipeline.NodeCounters.received:type_name -> avpipeline.NodeCountersSection
	3,  // 4: avpipeline.NodeCounters.processed:type_name -> avpipeline.NodeCountersSection
	3,  // 5: avpipeline.NodeCounters.missed:type_name -> avpipeline.NodeCountersSection
	3,  // 6: avpipeline.NodeCounters.generated:type_name -> avpipeline.NodeCountersSection
	3,  // 7: avpipeline.NodeCounters.omitted:type_name -> avpipeline.NodeCountersSection
	3,  // 8: avpipeline.NodeCounters.sent:type_name -> avpipeline.NodeCountersSection
	4,  // 9: avpipeline.NodeCountersSection.packets:type_name -> avpipeline.NodeCountersSubSection
	4,  // 10: avpipeline.NodeCountersSection.frames:type_name -> avpipeline.NodeCountersSubSection
	5,  // 11: avpipeline.NodeCountersSubSection.unknown:type_name -> avpipeline.NodeCountersItem
	5,  // 12: avpipeline.NodeCountersSubSection.other:type_name -> avpipeline.NodeCountersItem
	5,  // 13: avpipeline.NodeCountersSubSection.video:type_name -> avpipeline.NodeCountersItem
	5,  // 14: avpipeline.NodeCountersSubSection.audio:type_name -> avpipeline.NodeCountersItem
	25, // 15: avpipeline.Frame.frame:type_name -> libav.Frame
	26, // 16: avpipeline.Frame.codec_context:type_name -> libav.CodecContext
	27, // 17: avpipeline.Frame.time_base:type_name -> libav.Rational
	9,  // 18: avpipeline.AutoBitrateCalculator.thresholds:type_name -> avpipeline.AutoBitRateCalculatorThresholds
	19, // 19: avpipeline.AutoBitrateCalculator.log_k:type_name -> avpipeline.AutoBitrateCalculatorLogK
	20, // 20: avpipeline.AutoBitrateCalculator.queue_size_gap_decay:type_name -> avpipeline.AutoBitrateCalculatorQueueSizeGapDecay
	10, // 21: avpipeline.MovingAverageConfig.mama:type_name -> avpipeline.MovingAverageConfigMAMA
	11, // 22: avpipeline.MovingAverageConfig.other:type_name -> avpipeline.MovingAverageConfigOther
	14, // 23: avpipeline.FPSReducerConfig.ranges:type_name -> avpipeline.FPSReductionRange
	13, // 24: avpipeline.AutoBitRateResolutionAndBitRateConfig.resolution:type_name -> avpipeline.Resolution
	16, // 25: avpipeline.AutoBitRateResolutionAndBitRateConfigs.configs:type_name -> avpipeline.AutoBitRateResolutionAndBitRateConfig
	17, // 26: avpipeline.AutoBitRateVideoConfig.resolutions_and_bit_rates:type_name -> avpipeline.AutoBitRateResolutionAndBitRateConfigs
	8,  // 27: avpipeline.AutoBitRateVideoConfig.calculator:type_name -> avpipeline.AutoBitrateCalculator
	15, // 28: avpipeline.AutoBitRateVideoConfig.fps_reducer:type_name -> avpipeline.FPSReducerConfig
	13, // 29: avpipeline.AutoBitRateVideoConfig.min_resolution:type_name -> avpipeline.Resolution
	13, // 30: avpipeline.AutoBitRateVideoConfig.max_resolution:type_name -> avpipeline.Resolution
	12, // 31: avpipeline.AutoBitrateCalculatorLogK.moving_average:type_name -> avpipeline.MovingAverageConfig
	12, // 32: avpipeline.AutoBitrateCalculatorQueueSizeGapDecay.derivative_smoothed:type_name -> avpipeline.MovingAverageConfig
	0,  // 33: avpipeline.MonitorRequest.event_type:type_name -> avpipeline.MonitorEventType
	28, // 34: avpipeline.MonitorEvent.stream:type_name -> libav.Stream
	29, // 35: avpipeline.MonitorEvent.packet:type_name -> libav.Packet
	25, // 36: avpipeline.MonitorEvent.frames:type_name -> libav.Frame
	23, // 37: avpipeline.InputConfig.custom_options:type_name -> avpipeline.CustomOption
	38, // [38:38] is the sub-list for method output_type
	38, // [38:38] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_avpipeline_proto_init() }
func file_avpipeline_proto_init() {
	if File_avpipeline_proto != nil {
		return
	}
	file_avpipeline_proto_msgTypes[7].OneofWrappers = []any{
		(*AutoBitrateCalculator_Thresholds)(nil),
		(*AutoBitrateCalculator_LogK)(nil),
		(*AutoBitrateCalculator_Static)(nil),
		(*AutoBitrateCalculator_QueueSizeGapDecay)(nil),
	}
	file_avpipeline_proto_msgTypes[11].OneofWrappers = []any{
		(*MovingAverageConfig_Mama)(nil),
		(*MovingAverageConfig_Other)(nil),
	}
	file_avpipeline_proto_msgTypes[21].OneofWrappers = []any{}
	file_avpipeline_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avpipeline_proto_rawDesc), len(file_avpipeline_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_avpipeline_proto_goTypes,
		DependencyIndexes: file_avpipeline_proto_depIdxs,
		EnumInfos:         file_avpipeline_proto_enumTypes,
		MessageInfos:      file_avpipeline_proto_msgTypes,
	}.Build()
	File_avpipeline_proto = out.File
	file_avpipeline_proto_goTypes = nil
	file_avpipeline_proto_depIdxs = nil
}
