// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: avpipeline.proto

package avpipeline

import (
	libav "github.com/xaionaro-go/avpipeline/protobuf/libav"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avpipeline_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{0}
}

func (x *Object) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Object) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frame          *libav.Frame        `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	CodecContext   *libav.CodecContext `protobuf:"bytes,2,opt,name=codecContext,proto3" json:"codecContext,omitempty"`
	StreamIndex    int32               `protobuf:"varint,3,opt,name=streamIndex,proto3" json:"streamIndex,omitempty"`
	StreamsCount   int32               `protobuf:"varint,4,opt,name=streamsCount,proto3" json:"streamsCount,omitempty"`
	StreamDuration int64               `protobuf:"varint,5,opt,name=streamDuration,proto3" json:"streamDuration,omitempty"`
	TimeBase       *libav.Rational     `protobuf:"bytes,6,opt,name=timeBase,proto3" json:"timeBase,omitempty"`
	Pos            int64               `protobuf:"varint,7,opt,name=pos,proto3" json:"pos,omitempty"`
	Duration       int64               `protobuf:"varint,8,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avpipeline_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_avpipeline_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_avpipeline_proto_rawDescGZIP(), []int{1}
}

func (x *Frame) GetFrame() *libav.Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *Frame) GetCodecContext() *libav.CodecContext {
	if x != nil {
		return x.CodecContext
	}
	return nil
}

func (x *Frame) GetStreamIndex() int32 {
	if x != nil {
		return x.StreamIndex
	}
	return 0
}

func (x *Frame) GetStreamsCount() int32 {
	if x != nil {
		return x.StreamsCount
	}
	return 0
}

func (x *Frame) GetStreamDuration() int64 {
	if x != nil {
		return x.StreamDuration
	}
	return 0
}

func (x *Frame) GetTimeBase() *libav.Rational {
	if x != nil {
		return x.TimeBase
	}
	return nil
}

func (x *Frame) GetPos() int64 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *Frame) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_avpipeline_proto protoreflect.FileDescriptor

var file_avpipeline_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x76, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x61, 0x76, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x1a, 0x0b,
	0x6c, 0x69, 0x62, 0x61, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x06, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xad, 0x02,
	0x0a, 0x05, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x69, 0x62, 0x61, 0x76, 0x2e, 0x46,
	0x72, 0x61, 0x6d, 0x65, 0x52, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x63,
	0x6f, 0x64, 0x65, 0x63, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x69, 0x62, 0x61, 0x76, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x0c, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x61, 0x73, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x69, 0x62, 0x61, 0x76, 0x2e, 0x52, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x70, 0x6f,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x42, 0x5a,
	0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x61, 0x69, 0x6f,
	0x6e, 0x61, 0x72, 0x6f, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x76, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x76, 0x70, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x3b, 0x61, 0x76, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_avpipeline_proto_rawDescOnce sync.Once
	file_avpipeline_proto_rawDescData = file_avpipeline_proto_rawDesc
)

func file_avpipeline_proto_rawDescGZIP() []byte {
	file_avpipeline_proto_rawDescOnce.Do(func() {
		file_avpipeline_proto_rawDescData = protoimpl.X.CompressGZIP(file_avpipeline_proto_rawDescData)
	})
	return file_avpipeline_proto_rawDescData
}

var file_avpipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_avpipeline_proto_goTypes = []interface{}{
	(*Object)(nil),             // 0: avpipeline.Object
	(*Frame)(nil),              // 1: avpipeline.Frame
	(*libav.Frame)(nil),        // 2: libav.Frame
	(*libav.CodecContext)(nil), // 3: libav.CodecContext
	(*libav.Rational)(nil),     // 4: libav.Rational
}
var file_avpipeline_proto_depIdxs = []int32{
	2, // 0: avpipeline.Frame.frame:type_name -> libav.Frame
	3, // 1: avpipeline.Frame.codecContext:type_name -> libav.CodecContext
	4, // 2: avpipeline.Frame.timeBase:type_name -> libav.Rational
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_avpipeline_proto_init() }
func file_avpipeline_proto_init() {
	if File_avpipeline_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_avpipeline_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_avpipeline_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_avpipeline_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_avpipeline_proto_goTypes,
		DependencyIndexes: file_avpipeline_proto_depIdxs,
		MessageInfos:      file_avpipeline_proto_msgTypes,
	}.Build()
	File_avpipeline_proto = out.File
	file_avpipeline_proto_rawDesc = nil
	file_avpipeline_proto_goTypes = nil
	file_avpipeline_proto_depIdxs = nil
}
