// Tests auto-generated by AI agent.
package voiceanon

import (
	"sync/atomic"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestNewAnonymizer(t *testing.T) {
	va := NewAnonymizer(nil)
	assert.NotNil(t, va)
	assert.Nil(t, va.Enabled)
	assert.Equal(t, 0.7, va.Config().PitchScale)
}

func TestNewAnonymizer_WithEnabled(t *testing.T) {
	enabled := &atomic.Bool{}
	enabled.Store(true)
	va := NewAnonymizer(enabled)
	assert.NotNil(t, va)
	assert.True(t, va.Enabled.Load())
}

func TestNewAnonymizerWithPitch(t *testing.T) {
	va := NewAnonymizerWithPitch(nil, 1.5)
	assert.NotNil(t, va)
	assert.Equal(t, 1.5, va.Config().PitchScale)
}
