// Tests auto-generated by AI agent.
package whisper

import (
	"context"
	"testing"
	"time"

	"github.com/asticode/go-astiav"
	testifyassert "github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/avpipeline/frame"
	closuresignalerPkg "github.com/xaionaro-go/avpipeline/helpers/closuresignaler"
	"github.com/xaionaro-go/avpipeline/kernel"
	"github.com/xaionaro-go/avpipeline/kernel/avfilter"
	"github.com/xaionaro-go/avpipeline/packet"
	"github.com/xaionaro-go/avpipeline/packetorframe"
	packetorframetypes "github.com/xaionaro-go/avpipeline/packetorframe/types"
	globaltypes "github.com/xaionaro-go/avpipeline/types"
)

func makeAudioFrameInput(t *testing.T) (packetorframe.InputUnion, func()) {
	t.Helper()
	cp := astiav.AllocCodecParameters()
	cp.SetMediaType(astiav.MediaTypeAudio)
	cp.SetSampleRate(44100)
	cp.SetSampleFormat(astiav.SampleFormatFlt)
	cp.SetChannelLayout(astiav.ChannelLayoutMono)
	f := astiav.AllocFrame()
	streamInfo := &packetorframetypes.StreamInfo{
		CodecParameters: cp,
		StreamIndex:     0,
		StreamsCount:    1,
		TimeBase:        astiav.NewRational(1, 44100),
	}
	frameInput := frame.BuildInput(f, 0, streamInfo)
	cleanup := func() {
		cp.Free()
		f.Free()
	}
	return packetorframe.InputUnion{Frame: &frameInput}, cleanup
}

func makeVideoFrameInput(t *testing.T) (packetorframe.InputUnion, func()) {
	t.Helper()
	cp := astiav.AllocCodecParameters()
	cp.SetMediaType(astiav.MediaTypeVideo)
	f := astiav.AllocFrame()
	f.SetWidth(64)
	f.SetHeight(64)
	streamInfo := &packetorframetypes.StreamInfo{
		CodecParameters: cp,
		StreamIndex:     0,
		StreamsCount:    1,
	}
	frameInput := frame.BuildInput(f, 0, streamInfo)
	cleanup := func() {
		cp.Free()
		f.Free()
	}
	return packetorframe.InputUnion{Frame: &frameInput}, cleanup
}

func makePacketInput(t *testing.T) (packetorframe.InputUnion, func()) {
	t.Helper()
	cp := astiav.AllocCodecParameters()
	cp.SetMediaType(astiav.MediaTypeAudio)
	pkt := astiav.AllocPacket()
	streamInfo := &packetorframetypes.StreamInfo{
		CodecParameters: cp,
		StreamIndex:     0,
		StreamsCount:    1,
	}
	pktInput := packet.BuildInput(pkt, streamInfo)
	cleanup := func() {
		cp.Free()
		pkt.Free()
	}
	return packetorframe.InputUnion{Packet: &pktInput}, cleanup
}

// --- Constructor tests ---

func TestNew_NilConfig(t *testing.T) {
	_, err := New(context.Background(), nil, 0, nil, astiav.Rational{})
	testifyassert.Error(t, err)
	testifyassert.Contains(t, err.Error(), "config is nil")
}

func TestNew_MissingModel(t *testing.T) {
	cfg := DefaultWhisperConfig()
	_, err := New(context.Background(), cfg, 0, nil, astiav.Rational{})
	testifyassert.Error(t, err)
	testifyassert.Contains(t, err.Error(), "model path is required")
}

// --- Interface compliance ---

func TestWhisper_ImplementsAbstract(t *testing.T) {
	var _ kernel.Abstract = (*Whisper)(nil)
}

// --- String ---

func TestWhisper_String(t *testing.T) {
	w := &Whisper{
		Config: WhisperConfig{
			Model:    "/path/to/model.bin",
			Language: "en",
		},
	}
	s := w.String()
	testifyassert.Contains(t, s, "Whisper")
	testifyassert.Contains(t, s, "/path/to/model.bin")
	testifyassert.Contains(t, s, "en")
}

// --- GetObjectID ---

func TestWhisper_GetObjectID(t *testing.T) {
	w := &Whisper{
		Config: WhisperConfig{Model: "m.bin"},
	}
	id := w.GetObjectID()
	testifyassert.NotEmpty(t, id)
}

// --- Generate ---

func TestWhisper_Generate(t *testing.T) {
	w := &Whisper{}
	outputCh := make(chan packetorframe.OutputUnion, 10)
	err := w.Generate(context.Background(), outputCh)
	testifyassert.NoError(t, err)
	testifyassert.Len(t, outputCh, 0)
}

// --- Close ---

func TestWhisper_Close_NilFilterGraph(t *testing.T) {
	w := &Whisper{
		ClosureSignaler: closuresignalerPkg.New(),
	}
	err := w.Close(context.Background())
	testifyassert.NoError(t, err)
}

// --- SendInput passthrough tests ---

func TestWhisper_SendInput_PassthroughPacket(t *testing.T) {
	w := &Whisper{
		ClosureSignaler: closuresignalerPkg.New(),
	}
	input, cleanup := makePacketInput(t)
	defer cleanup()

	outputCh := make(chan packetorframe.OutputUnion, 10)
	err := w.SendInput(context.Background(), input, outputCh)
	testifyassert.NoError(t, err)
	testifyassert.Len(t, outputCh, 1)

	out := <-outputCh
	testifyassert.NotNil(t, out.Packet)
	testifyassert.Nil(t, out.Frame)
}

func TestWhisper_SendInput_PassthroughVideoFrame(t *testing.T) {
	w := &Whisper{
		ClosureSignaler: closuresignalerPkg.New(),
	}
	input, cleanup := makeVideoFrameInput(t)
	defer cleanup()

	outputCh := make(chan packetorframe.OutputUnion, 10)
	err := w.SendInput(context.Background(), input, outputCh)
	testifyassert.NoError(t, err)
	testifyassert.Len(t, outputCh, 1)

	out := <-outputCh
	testifyassert.NotNil(t, out.Frame)
}

func TestWhisper_SendInput_NilInput(t *testing.T) {
	w := &Whisper{
		ClosureSignaler: closuresignalerPkg.New(),
	}
	outputCh := make(chan packetorframe.OutputUnion, 10)
	err := w.SendInput(context.Background(), packetorframe.InputUnion{}, outputCh)
	testifyassert.NoError(t, err)
	// Empty union: CloneAsReferencedOutput returns nil Get(), so output may be empty
}

// --- SendInput audio path tests (using anull filter to test delegation) ---

func newTestWhisperWithAnull(t *testing.T, ctx context.Context) (*Whisper, func()) {
	t.Helper()
	cp := astiav.AllocCodecParameters()
	cp.SetMediaType(astiav.MediaTypeAudio)
	cp.SetSampleRate(16000)
	cp.SetSampleFormat(astiav.SampleFormatFlt)
	cp.SetChannelLayout(astiav.ChannelLayoutMono)

	trackConfig := map[int]avfilter.TrackConfig{
		0: {
			CodecParameters: cp,
			TimeBase:        astiav.NewRational(1, 16000),
		},
	}
	graph, err := avfilter.NewGraph(ctx, trackConfig, "[in0]anull[out0]")
	require.NoError(t, err)

	w := &Whisper{
		ClosureSignaler: closuresignalerPkg.New(),
		Config:          WhisperConfig{Model: "test.bin", Language: "en"},
		filterGraph:     kernel.NewAVFilterGraph(ctx, graph),
	}
	cleanup := func() {
		w.Close(ctx)
		cp.Free()
	}
	return w, cleanup
}

func makeAllocatedAudioFrame(t *testing.T, numSamples int) (*astiav.Frame, *astiav.CodecParameters) {
	t.Helper()
	f := astiav.AllocFrame()
	f.SetSampleFormat(astiav.SampleFormatFlt)
	f.SetChannelLayout(astiav.ChannelLayoutMono)
	f.SetSampleRate(16000)
	f.SetNbSamples(numSamples)
	require.NoError(t, f.AllocBuffer(0))

	cp := astiav.AllocCodecParameters()
	cp.SetMediaType(astiav.MediaTypeAudio)
	cp.SetSampleRate(16000)
	cp.SetSampleFormat(astiav.SampleFormatFlt)
	cp.SetChannelLayout(astiav.ChannelLayoutMono)

	return f, cp
}

func TestWhisper_SendInput_AudioFrame_ThroughFilterGraph(t *testing.T) {
	ctx := context.Background()
	w, cleanup := newTestWhisperWithAnull(t, ctx)
	defer cleanup()

	f, cp := makeAllocatedAudioFrame(t, 1024)
	defer f.Free()
	defer cp.Free()

	streamInfo := &packetorframetypes.StreamInfo{
		CodecParameters: cp,
		StreamIndex:     0,
		StreamsCount:    1,
		TimeBase:        astiav.NewRational(1, 16000),
	}
	frameInput := frame.BuildInput(f, 0, streamInfo)
	input := packetorframe.InputUnion{Frame: &frameInput}

	outputCh := make(chan packetorframe.OutputUnion, 10)
	err := w.SendInput(ctx, input, outputCh)
	testifyassert.NoError(t, err)
	testifyassert.Equal(t, 1, len(outputCh))

	out := <-outputCh
	require.NotNil(t, out.Frame)
	testifyassert.Equal(t, 0, out.Frame.StreamIndex)
}

func TestWhisper_SendInput_AudioFrame_MetadataExtracted(t *testing.T) {
	ctx := context.Background()
	w, cleanup := newTestWhisperWithAnull(t, ctx)
	defer cleanup()

	f, cp := makeAllocatedAudioFrame(t, 1024)
	defer f.Free()
	defer cp.Free()

	// Pre-set metadata on input frame; the anull filter preserves metadata.
	md := astiav.NewDictionary()
	require.NoError(t, md.Set("lavfi.whisper.text", "transcribed text", astiav.NewDictionaryFlags()))
	require.NoError(t, md.Set("lavfi.whisper.duration", "2500", astiav.NewDictionaryFlags()))
	f.SetMetadata(md)

	streamInfo := &packetorframetypes.StreamInfo{
		CodecParameters: cp,
		StreamIndex:     0,
		StreamsCount:    1,
		TimeBase:        astiav.NewRational(1, 16000),
	}
	frameInput := frame.BuildInput(f, 0, streamInfo)
	input := packetorframe.InputUnion{Frame: &frameInput}

	outputCh := make(chan packetorframe.OutputUnion, 10)
	err := w.SendInput(ctx, input, outputCh)
	testifyassert.NoError(t, err)
	require.Equal(t, 1, len(outputCh))

	out := <-outputCh
	require.NotNil(t, out.Frame)

	result, ok := globaltypes.PipelineSideDataLatest[*WhisperResult](out.Frame.GetPipelineSideData())
	require.True(t, ok)
	testifyassert.Equal(t, "transcribed text", result.Text)
	testifyassert.Equal(t, 2500*time.Millisecond, result.Duration)
}

func TestWhisper_SendInput_AudioFrame_ContextCancelled(t *testing.T) {
	ctx := context.Background()
	w, cleanup := newTestWhisperWithAnull(t, ctx)
	defer cleanup()

	f, cp := makeAllocatedAudioFrame(t, 1024)
	defer f.Free()
	defer cp.Free()

	streamInfo := &packetorframetypes.StreamInfo{
		CodecParameters: cp,
		StreamIndex:     0,
		StreamsCount:    1,
		TimeBase:        astiav.NewRational(1, 16000),
	}
	frameInput := frame.BuildInput(f, 0, streamInfo)
	input := packetorframe.InputUnion{Frame: &frameInput}

	cancelCtx, cancel := context.WithCancel(ctx)
	cancel()

	// Unbuffered channel so output send blocks, triggering ctx.Done path
	outputCh := make(chan packetorframe.OutputUnion)
	err := w.SendInput(cancelCtx, input, outputCh)
	testifyassert.Error(t, err)
	testifyassert.ErrorIs(t, err, context.Canceled)
}

func TestWhisper_Close_WithFilterGraph(t *testing.T) {
	ctx := context.Background()
	w, _ := newTestWhisperWithAnull(t, ctx)

	err := w.Close(ctx)
	testifyassert.NoError(t, err)
}

// --- Metadata extraction tests ---

func TestExtractWhisperMetadata_WithText(t *testing.T) {
	f := astiav.AllocFrame()
	defer f.Free()

	md := astiav.NewDictionary()
	require.NoError(t, md.Set("lavfi.whisper.text", "hello world", astiav.NewDictionaryFlags()))
	require.NoError(t, md.Set("lavfi.whisper.duration", "1500", astiav.NewDictionaryFlags()))
	f.SetMetadata(md)

	cp := astiav.AllocCodecParameters()
	defer cp.Free()
	cp.SetMediaType(astiav.MediaTypeAudio)

	output := frame.BuildOutput(f, &frame.StreamInfo{
		CodecParameters: cp,
	})

	extractWhisperMetadata(&output)

	result, ok := globaltypes.PipelineSideDataLatest[*WhisperResult](output.GetPipelineSideData())
	require.True(t, ok)
	testifyassert.Equal(t, "hello world", result.Text)
	testifyassert.Equal(t, 1500*time.Millisecond, result.Duration)
}

func TestExtractWhisperMetadata_NoMetadata(t *testing.T) {
	f := astiav.AllocFrame()
	defer f.Free()

	cp := astiav.AllocCodecParameters()
	defer cp.Free()
	cp.SetMediaType(astiav.MediaTypeAudio)

	output := frame.BuildOutput(f, &frame.StreamInfo{
		CodecParameters: cp,
	})

	extractWhisperMetadata(&output)

	_, ok := globaltypes.PipelineSideDataLatest[*WhisperResult](output.GetPipelineSideData())
	testifyassert.False(t, ok)
}

func TestExtractWhisperMetadata_EmptyText(t *testing.T) {
	f := astiav.AllocFrame()
	defer f.Free()

	md := astiav.NewDictionary()
	require.NoError(t, md.Set("lavfi.whisper.text", "", astiav.NewDictionaryFlags()))
	f.SetMetadata(md)

	cp := astiav.AllocCodecParameters()
	defer cp.Free()
	cp.SetMediaType(astiav.MediaTypeAudio)

	output := frame.BuildOutput(f, &frame.StreamInfo{
		CodecParameters: cp,
	})

	extractWhisperMetadata(&output)

	_, ok := globaltypes.PipelineSideDataLatest[*WhisperResult](output.GetPipelineSideData())
	testifyassert.False(t, ok)
}

func TestExtractWhisperMetadata_TextOnly_NoDuration(t *testing.T) {
	f := astiav.AllocFrame()
	defer f.Free()

	md := astiav.NewDictionary()
	require.NoError(t, md.Set("lavfi.whisper.text", "test transcript", astiav.NewDictionaryFlags()))
	f.SetMetadata(md)

	cp := astiav.AllocCodecParameters()
	defer cp.Free()
	cp.SetMediaType(astiav.MediaTypeAudio)

	output := frame.BuildOutput(f, &frame.StreamInfo{
		CodecParameters: cp,
	})

	extractWhisperMetadata(&output)

	result, ok := globaltypes.PipelineSideDataLatest[*WhisperResult](output.GetPipelineSideData())
	require.True(t, ok)
	testifyassert.Equal(t, "test transcript", result.Text)
	testifyassert.Equal(t, time.Duration(0), result.Duration)
}

func TestExtractWhisperMetadata_InvalidDuration(t *testing.T) {
	f := astiav.AllocFrame()
	defer f.Free()

	md := astiav.NewDictionary()
	require.NoError(t, md.Set("lavfi.whisper.text", "some text", astiav.NewDictionaryFlags()))
	require.NoError(t, md.Set("lavfi.whisper.duration", "not-a-number", astiav.NewDictionaryFlags()))
	f.SetMetadata(md)

	cp := astiav.AllocCodecParameters()
	defer cp.Free()
	cp.SetMediaType(astiav.MediaTypeAudio)

	output := frame.BuildOutput(f, &frame.StreamInfo{
		CodecParameters: cp,
	})

	extractWhisperMetadata(&output)

	result, ok := globaltypes.PipelineSideDataLatest[*WhisperResult](output.GetPipelineSideData())
	require.True(t, ok)
	testifyassert.Equal(t, "some text", result.Text)
	testifyassert.Equal(t, time.Duration(0), result.Duration)
}

func TestExtractWhisperMetadata_NilFrame(t *testing.T) {
	cp := astiav.AllocCodecParameters()
	defer cp.Free()
	cp.SetMediaType(astiav.MediaTypeAudio)

	output := frame.BuildOutput(nil, &frame.StreamInfo{
		CodecParameters: cp,
	})

	// Should not panic
	extractWhisperMetadata(&output)
}

func TestExtractWhisperMetadata_UnrelatedMetadata(t *testing.T) {
	f := astiav.AllocFrame()
	defer f.Free()

	md := astiav.NewDictionary()
	require.NoError(t, md.Set("some.other.key", "value", astiav.NewDictionaryFlags()))
	f.SetMetadata(md)

	cp := astiav.AllocCodecParameters()
	defer cp.Free()
	cp.SetMediaType(astiav.MediaTypeAudio)

	output := frame.BuildOutput(f, &frame.StreamInfo{
		CodecParameters: cp,
	})

	extractWhisperMetadata(&output)

	_, ok := globaltypes.PipelineSideDataLatest[*WhisperResult](output.GetPipelineSideData())
	testifyassert.False(t, ok)
}
